### ISSUE TITLE
Paragraaf 4.9.3 CRS negotiation

### ISSUE THREAD

**Issue by jasperroes** [Geonovum/KP-APIs#121]
Opmerkingen uit review-formulier:

GeoData uit de API moet altijd eenvoudig beschikbaar gesteld worden in het CRS van de brondata, voor Nederland in verreweg de meeste gevallen RD (Kadaster, bestemmingsplannen, BAG, BRT, BGT). RD is noordgericht en in meters en maakt meten, schalen en het bepalen van oppervlakte heel eenvoudig. 

-----
Transformatie van het ene CRS naar het andere levert altijd afrondings verschillen op. Bevragen en leveren van geometrie in iets anders dan het bron CRS kan dan onbedoelde verschillen opleveren.

Voorgestelde oplossing:
Het bevragen van geometrie voor mutatie moet *altijd* in het bron CRS.Het leveren van geometrie moet *altijd* in het bron CRS.

-----
GeoJSON kan BGT geometrieen niet correct opslaan, het kan geen compound geometries. Voorgestelde oplossing: GML als content type toestaan ?

----
Wat betekent de zin "Leg als bronsysteem binnenkomende formaat vast (juridische context);" ?

**Comment by jasperroes** [comment]
In de API strategie opnemen dat in de documentatie van de API gedefinieerd moet zijn wat de bron CRS is + welke transformatiemethode er gebruikt wordt + definieren hoe je in de geojson body op kunt geven wat de bron CRS is.

GML wordt niet toegevoegd als content type omdat we verwachten dat voor dit soort zaken een geo koppelvlak gebruikt wordt (bijvoorbeeld WFS).

**Comment by sergei-maertens** [comment]
> definieren hoe je in de geojson body op kunt geven wat de bron CRS is

Dit zat oorspronkelijk in de GeoJSON draft, maar is er finaal uitgehaald. Als je dit opneemt, dan pas je niet meer de GeoJSON standaard toe, toch?

**Comment by jasperroes** [comment]
Klopt, maar we hebben het wel nodig dus hebben we voor deze oplossing gekozen. Documentatie is aangepast.
