### ISSUE TITLE
Overall, taal

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/KP-APIs#131]
Opmerkingen via webforumlier:
--

Taal:     Er worden nu zaken in het Nederlands gebruikt dit beter passen in een   Engels kader. Zoals bv zoeken filteren en sort by asc en desc, fields. Hier   heb je ook te maken met tools en libraries die hier standaarden hebben.     In dit document: Bv designrules en verder op beveiliging gaat ipv security.   Maak het uniform. Voorkeur heeft dan al dit soort termen in het Engels te   nemen.

**Comment by LeoZandvliet** [comment]
T.b.v. de Developer Experience (ongeacht het werkveld) is het in ieder geval aan te raden één taal aan te houden. I.g.v. internationalisering en aansluiting bij breed geaccepteerde technieken (#130) is Engels de betere keuze. Enkel de resources in Nederlands is dan nog een aardige 'trade off' als er geen goede 'glossary' aanwezig is. Persoonlijk zou ik dit omdraaien: er wordt een goed woordenboek van definities aangelegd **omdat** er een goede (Engelstalige) API gemaakt moet gaan worden.

**Comment by jasperroes** [comment]
Omgezet naar Engels.
