### ISSUE TITLE
Algemeen, focus op bevragen

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/KP-APIs#132]
Opmerkingen binnengekomen via webformulier:
--

In   het document wordt de focus gelegd bij het ontsluiten en bevragen van   data-sets middels API's. Zie ook de voorbeelden die genoemd worden in   paragraaf 9.          Bij veel van de informatieverwerkende processen van onze klanten gaat het   juist om mutatieverwerking en gegevens-synchronisatie.

oplossing
Besteed   meer aandacht aan de informatieverwerkende processen gericht op   mutatie-verwerking en synchronisatie die met een API-infrastructuur   gefaciliteerd worden, naast de processen voor bevragen.

**Comment by mrtn78** [comment]
dit moeten we duidelijker uitwerken in par 14. de reading guide waarin ook expliciet verwezen kan worden naar de architectuur  van de API Strategie waarin we dit verder beschrijven.

**Comment by mrtn78** [comment]
De expliciete verwijzing van de API Design Rules naar de Architectuur is gemaakt maar wellicht in de Architectuur nog verder benadrukken

**Comment by mrtn78** [comment]
Gesloten tijdens werkgroep / TO ADR 25-04-2024
