### ISSUE TITLE
Versioning & links tussen verschillende API's

### ISSUE THREAD

**Issue by CathyDingemanse** [Geonovum/KP-APIs#157]
Met Jasper Roes afgesproken dat Haal Centraal BRP-bevragen een voorstel zouden doen n.a.v. #7.

**Comment by MelvLee** [comment]
Er zijn 4 manieren bekend om API's te versionen:

1. Versie in de URI
V.b. https://www.haalcentraal.nl/haalcentraal/api/v1/brp/ingeschrevenpersonen
Voordeel:
- expliciet. Aan de URI is direct op te maken welke versie van de API wordt gebruikt
- Deze manier van versioning wordt veel gebruikt en is hierdoor bekend bij ontwikkelaars
Nadeel: Doorlinken naar externe resources is complex. Hoeveel versies zijn er van de externe resource? Welke versie van de externe resource gebruikt de consumer?

2. Versie in een Query String parameter
V.b. https://www.haalcentraal.nl/haalcentraal/api/brp/ingeschrevenpersonen?v=1
Voordeel:
- URI blijft bij nieuwe versie gelijk als versie een optionele parameter is
- Als versie parameter optioneel is, dan wordt bij het niet opgeven van de parameter de laatste versie van de Resourc geretourneerd
Nadeel:
- impliciet. Als de versie Query String parameter niet wordt meegegeven, dan is het niet direct op te maken welke versie van de API wordt/is gebruikt. Expliciet maken van de versie Query String parameter maakt het onderdeel van de URI en heb je dezelfde nadelen als versie in de URI
- Versie is een technisch parameter. Andere parameters zijn (hoogst waarschijnlijk) functioneel

3. Versie via content type (content negotiation)
Voordeel:
- URI blijft bij nieuwe versie gelijk
- Een nieuwe versie is een andere representatie van een Resource
Nadeel:
- elke versie betekent een specifiek content type
- Er kan geen gebruik worden gemaakt van de standaard content types (application/json, application/hal+json). Er moet een eigen content type worden bedacht, bijvoorbeeld: vnd.brp.v1/hal+json

4. Versie via een custom header
Voordeel:
- URI blijft bij nieuwe versie gelijk
- Custom header kan optioneel worden gemaakt. Als deze niet wordt opgegeven, dan krijgt de consumer de laatste versie van de Resource
Nadeel: impliciet. Het is niet direct op te maken welke versie van de Resource wordt bevraagd

Wanneer BRP wil kunnen linken naar externe resources, dan is optie 1 geen goede keuze.
Optie 3 levert meer werk op voor zowel provider als consumers. Elke nieuwe versie betekent een nieuwe content type.
Er is weinig verschil tussen optie 2 en optie 4. Optie 2 is minder zuiver omdat een technische parameter tussen de functionele parameters staat. Als de API functioneel zuiver gehouden moet worden, dan is optie 4 de beste keuze.

**Comment by fsamwel** [comment]
Volgens https://geonovum.github.io/KP-APIs/#versioning is er al een API-version request header gedefinieerd, waarmee de minor versie kan worden opgegeven. Daarmee is m.i. de custom header voor optie 4 al gevonden. Wanneer een andere optie dan 4 (of 1) wordt gekozen, zou m.i. ook de api-version request header moeten vervallen. Het lijkt me namelijk nogal verwarrend om de major versie te vragen op een manier en de minor versie op een ander manier (bijvoorbeeld tegelijk een request header api-version én een query parameter version.

**Comment by jasperroes** [comment]
Is sluit deze, versionering blijft gelijk, dus major versienummer in de URL, discussie over links tussen API kan verder in https://github.com/Geonovum/KP-APIs/issues/7

**Comment by lvanderree** [comment]
is er ook nog een argumentatie achter waarom deze discussie gesloten is @jasperroes ? Waarom wordt er bijv. van de veel gebruikte en goed gedocumenteerde Zalando standaarden (zie https://opensource.zalando.com/restful-api-guidelines/#114 ) afgeweken die dit en heel veel anders allemaal al hebben uitgewerkt en uitgedacht?

**Comment by CathyDingemanse** [comment]
@lvanderree wij van Haal Centraal zijn het met jou eens. Wij zijn "overstag gegaan" vanwege het argument van dat de versie in de URL wereldwijd het meest gangbaar is. Niet op inhoud dus.

**Comment by lvanderree** [comment]
Dat argument heb ik inderdaad voorbij zien komen, en ik herken ook zeker het gebruik van versies in de URL in diverse API's, maar ik ken toch ook genoeg grote APIs die zonder versie nummer in de URL ingericht zijn, zie bijv ook: https://developer.github.com/v3/media/#request-specific-version lijkt me toch ook geen kleine speler
