### ISSUE TITLE
Extensie - 3.1.2. Openbare identifiers

### ISSUE THREAD

**Issue by LeoZandvliet** [Geonovum/KP-APIs#165]
[3.1.2. Openbare identifiers](https://geonovum.github.io/KP-APIs/Werkgroep%20API%20strategie/extensies/#x3-1-2-openbare-identifiers)
Ik vind het een rare aanbeveling om UUID's base64 te encoderen t.b.v. gebruik in API calls.
Een UUID is al url safe.
Als het om het inkorten van de UUID gaat vind ik dat ook wat onzinnig, 
een base64 bewerking om 14 karakters te besparen. Dat valt in het niet bij het comprimeren op http niveau (gzip).

**Comment by joostfarla** [comment]
Paragraaf is onlangs verwijderd (zie https://github.com/Geonovum/KP-APIs/commit/a697db5c80fd540476f19e4ee913492d766cc1d7).
