### ISSUE TITLE
extension document onduidelijkheden en verbeteringen 

### ISSUE THREAD

**Issue by GeertsP** [Geonovum/KP-APIs#183]
Wat is precies het oogmerk van het extension document?
De set normatieve API rules in dit document is exact hetzelfde als het basis document dus wat zijn nu extensies?  
Verder is de nummering van deze lijst voor verbetering vatbaar omdat API-07/08 niet blijken te bestaan? 
Elk hoofdstuk (als container voor een aantal api-rules) uit het document  wordt gestart met een rood waarschuwingsblok (icoon). Betekent dit dat nog niets van de rules is vastgesteld en alles nog kan wijzigen?

**Comment by fterpstra** [comment]
Het extension document is nog in ontwikkeling. Mogelijk wanneer een extensie uitontwikkeld is kan hij aan de normatieve API-design rules worden toegevoegd of als optionele extensie worden toegepast.
API principes worden doorgenummerd zodat er van buiten het document uniek naar te verwijzen is. Een aantal is alweer vervallen, vandaar de gaten. we zullen dit toelichten bij de principes.
De aanname is correct dat van de extensies momenteel nog niets is vastgesteld

**Comment by GeertsP** [comment]
Frank,
 Wat ik nog steeds niet goed begrijp is dat de set aan API standaarden qua
nummering en inhoud in zowel het normatieve als extensie document exact
hetzelfde is. Zou het extensie document niet tenminste het nodige aan
nieuwe aanvullende zaken t.o.v. de standaard moeten bevatten.
Ik zie die namelijk niet
Mvg PeterGeerts

Op di 5 nov. 2019 16:12 schreef Frank Terpstra <notifications@github.com>:

**Comment by fterpstra** [comment]
Hoi Geert,
Je doelt denk ik op de API principes die in beide documenten hetzelfde zijn? dat zijn we momenteel aan het aanpassen. In ieder document komen alleen die API principes waarnaar in dat document gerefereerd wordt. De principes krijgen ook dezelfde status als de tekst waarin naar ze gerefereerd wordt.
groeten
Frank
