### ISSUE TITLE
API's als hulp in de strijd tegen het Corona-virus

### ISSUE THREAD

**Issue by HenriKorver** [Geonovum/KP-APIs#202]
[![afbeelding](https://user-images.githubusercontent.com/37145898/77742082-304a7980-7016-11ea-9a52-78a29992cbe6.png)](https://covid-19-apis.postman.com/?mkt_tok=eyJpIjoiWm1SaVpXUmhOakZqWmpBMSIsInQiOiJ0ZzlFNXFPQWlLZDV2eXV3UGNGeDE1MnNqa3hQM2ZaR3NaV3VEV2l3Nk5iV05NeFlYVDlyYnFveldqeUlrYTRzM2doMHk3dWRIMTlaRVFpN2pVc0xcL1UxK1hzUG1vMVVWdG5PRExocDY5NU14WjRLcHpsRXRFTmdpM1wvYUhxclYxIn0%3D)

**Comment by mrtn78** [comment]
goed punt. dit mag ieder voor zich oppakken en er kennis van nemen.
