### ISSUE TITLE
API-10: Implement operations that do not fit the CRUD model as sub-resources

### ISSUE THREAD

**Issue by frankvanes** [Geonovum/KP-APIs#213]
API-10: Implement operations that do not fit the CRUD model as sub-resources
--> Deze is naar mijn idee iets te stellig. De use cases die ik ook beschrijf in issue #208 voor de POST operatie zijn hier m.i. sowieso uitzonderingen op.
Stel dat je bijvoorbeeld een resource collectie van documenten hebt met de volgende operaties:
POST /documenten : voeg een nieuw document toe
GET /documenten : ophalen overzicht van alle documenten
GET /documenten/{doc-id} : ophalen van informatie over document {doc_id}
PUT /documenten/{doc-id} : aanpassen van document {doc_id}

In dit geval zou een POST /documenten/{doc-id} een prima operatie kunnen zijn om het document {doc_id} te versturen, bijvoorbeeld naar de back-office ter akkordering of per mail. Hier hoeft geen sub-resource voor te worden geïntroduceerd.

**Comment by joostfarla** [comment]
De tekst heb ik zojuist wat verduidelijkt. De door jou genoemde use case valt eigenlijk onder approach 3. Dat zou in dat geval bijvoorbeeld zijn:

```
POST /documenten/{doc-id}/_verzend
```

Een `POST` naar `/documenten/{doc-id}` vind ik persoonlijk wat verwarrend, omdat uit de URI/method combi dan niet is af te leiden wat de intent van dit request is. Deze naming conventie helpt om dat expliciet te maken.

**Comment by joostfarla** [comment]
Aanpassingen akkoord bevonden door werkgroep.
