### ISSUE TITLE
Allow yaml in principle 3.15

### ISSUE THREAD

**Issue by jzuidweg** [Geonovum/KP-APIs#226]
_I received this issue from the [internet.nl](https://internet.nl/) developer community:_

We 'd like to relax principle 3.15 of the API Design Rules to also include **yaml**.
As they specifically mention in OAS 3.0, yaml is an option too. See: [http://spec.openapis.org/oas/v3.0.3#format](http://spec.openapis.org/oas/v3.0.3#format)

**Comment by fsamwel** [comment]
yaml is an option too, so you can publish both json and yaml. I think the goal is not to minimise work for the provider, but to minimise and ease work for the consumer (DX).
Exporting of transforming yaml to json is pretty simple for the provider, can be automated in the build process, etc. So I don't really understand the issue with publishing specifications in json format

**Comment by PieterHering** [comment]
Just to clarify your request,  rule [**API-51**](https://publicatie.centrumvoorstandaarden.nl/api/adr/static.html#api-51) states: 

> **API 51: Publish OAS document at a standard location in JSON-format.**
> (...) 
> At least the JSON format must be supported. When having multiple (major) versions of an API, every API should provide its own OAS document(s).
> >An API having base path https://api.example.org/v1/ must publish the OAS document at:
> > https://api.example.org/v1/openapi.json 
> > Optionally, the same OAS document *may be provided in YAML format:*
> > https://api.example.org/v1/openapi.yaml

So, yaml is currently allowed, but only optionally. 

Do we understand your request correctly  that Providers should be **required** to publish the OAS  **both**  in YAML and JSON format? Or is the fact that YAML is optionally allowed sufficient (and no change on this rule is necessary)?

**Comment by joostfarla** [comment]
In design rule [API-51](https://publicatie.centrumvoorstandaarden.nl/api/adr/#api-51), the YAML format is already allowed. Therefore, closing this issue.
