### ISSUE TITLE
Typos in API Design Rules

### ISSUE THREAD

**Issue by jzuidweg** [Geonovum/KP-APIs#227]

**Comment by jzuidweg** [comment]
_The [internet.nl](https://internet.nl/) community notified me that they found scores of typos in de API Design Rules. A selection:_

"**THis** version of the desgnrules"
"existing documentation in **Engelish**"
"official English glossary **avaialble**"
"Minor and patch versions have no impact on existing code, but major **version** do"
"design rules or **prinicples** for APIs"
"**prinicple** of REST is the **seperation** of the API"
 "because clients and **middelware**"

**Comment by joostfarla** [comment]
Typo's zijn opgelost.
