### ISSUE TITLE
API principe 06 - How to go deal with relations

### ISSUE THREAD

**Issue by LeoZandvliet** [Geonovum/KP-APIs#258]
Twee textuele opmerkingen:
- How to ~~**go**~~ deal with relations
- If a relation can only exist in the contex**~~s~~**t of another resource (1 to n relation)

Verder vind ik het té stellig om te zeggen dat bij 1 op N relaties de gerelateerde entiteit alleen als subentiteit opgevraagd kan worden.
Twee scenario's:

- Een `product` heeft een verplicht veld `categorie`
  `product` kan niet bestaan als `categorie` niet ingevuld is.
- Een `product` heeft een N:M relatie met `categorie`
  `product` is niet zichtbaar in de webshop als er géén enkele relatie met `categorie` is.

Als ik nu paragraaf 4.2.4 volg, en ik heb een API op de webshop beschikbaar, zou ik in geen van beide scenario's binnen 'alle producten' kunnen zoeken en ben ik verplicht om per categorie een zoekopdracht te doen. De resource `/producten` is immers niet beschikbaar (of zelfs: mag niet aangeboden worden)?

**Comment by mrtn78** [comment]
Gesloten tijdens werkgroep / TO ADR 25-04-2024
De voorgestelde verbetering is meegenomen in ADR 2
