### ISSUE TITLE
Links tussen verschillende API's

### ISSUE THREAD

**Issue by dvh** [Geonovum/KP-APIs#283]
Met HATEOAS kunnen we navigeren binnen API's. Door absolute URL's in plaats van relatieve URL's te gebruiken kunnen we ook linken naar andere API's (bijv. van een BAG pand `bag.basisregistraties.overheid.nl/api/v1/panden/123` naar een BRK perceel `brk.basisregistraties.overheid.nl/v1/percelen/234`).

Echter, wat gebeurt er als de URL structuur van een van de API's verandert? In het voorbeeld zou de BRK een `v2` kunnen lanceren waardoor de URL verandert naar `brk.basisregistraties.overheid.nl/v2/percelen/234`. Bovendien hoeft een nieuwe major versie als deze niet backwards compatible te zijn, dus ook de inhoud van de API responses kan anders zijn. Clients die beide API's bevragen en de 'convenience' link van de BAG naar de BRK gebruiken kunnen hierdoor in de problemen komen.

Een mogelijke oplossing kan zijn om de versie van de API waarnaar gelinkt wordt expliciet op te nemen in het link object naar de API, waarbij de beschikbaarheid van de links gelijk loopt met de beschikbare versies van die API bijvoorbeeld:

```
_links: {
  brkPerceelV1: {
    href: 'https://brk.basisregistraties.overheid.nl/v1/percelen/234'
  },
  brkPerceelV2: {
    href: 'https://brk.basisregistraties.overheid.nl/v2/percelen/234'
  },
}
```

Hierover moeten wel afspraken gemaakt worden, bijvoorbeeld dat de link naar `v2` wordt toegevoegd zo snel mogelijk nadat `v2` gereleased is, en dat de link naar `v1` wordt weggehaald op het moment (of zo kort mogelijk daarvoor) dat `v1` uit de lucht wordt gehaald.

**Comment by PvdZijden** [comment]
Op voorhand mijn excuses voor het bumpen van een issue waar al meer dan een jaar geen comment meer op geplaatst is.
Bij het lezen van alle comments die hierop geboekt zijn kreeg ik de drang om wat bij te dragen. Het lijkt mij dat de discussie ietwat door elkaar of langs elkaar loopt, maar mogelijk bijna bij het eindpunt is.

Mijn redenatie:
Als het doel is om over API- en/of resource-grenzen heen te verbinden zou het hele principe van API's en integratie ons al moeten vertellen hoe we dat aanpakken. Ont-koppelen, abstraheren en de techniek in de techniek laten, en de data bij de data. Kortom, in mijn beperkte visie is een verwijzing over de grens van een API/resource/domein/sector/etc altijd op data gebaseerd, nooit op een technisch (implementatie) gegeven of detail, dat gaat namelijk direct ten kosten van de autonomy van API ontwikkeling, de weg naar de 'distributed monolith'. Het concept en de verhouding van URL en URI zijn hierin ietwat misleidend en werkt de verwarring in de hand.
Dit neemt ook niet weg dat je best kan 'hinten' met extra gegevens over waar je eventuele vervolgvragen kan stellen natuurlijk. Echter, je operationele belangen of reputatie mogen mijns inziens nooit hangen op het feit of een andere organisatie wel goed bijhoud welke versie/URL van jouw API in zijn of haar API naar verwezen wordt. Als je een dergelijke situatie laat ontstaan denk ik dat je een aanzienlijke risico implementeert voor een cascade aan falen, een serieuze kwetsbaarheid dus. 
Volgens mij is de wens 'om data te koppelen' maar als oplossing wordt de techniek gekoppeld, niet de data.

Discoverability is iets moois, maar daar zijn ook nog andere middelen voor, 'in-response' discoverability is niet iets noodzakelijks op alle API's lijkt mij. 
Als we kunnen aannemen dat echte eindgebruikers (uitvoerend in het bedrijfsproces) altijd voorzien worden van enige visualisatie/presentatie, en zij (zoals al is gezegd) niet zelfstandig headers mee zullen/kunnen sturen (dus ook geen API-keys), dan zijn zij niet de de doelgroep voor deze manier van discoverability. 
De doelgroep van gebruik [van deze discoverability] is wat mij betreft beperkt tot ontwikkelaars die, op niet-productie omgevingen, op het verkennende pad zijn. Impact op uitvoering van bedrijfsprocessen/taken zou dan dus ook 0 (nul) moeten zijn, impact op de wendbaarheid minimaal, dit is immers convenience linken toch?
Wat betreft de kwetsbaarheid van eindgebruiker-oplossingen voor de API versionering bij een 'aanbieder' zogezegd, zou dat net als nu geen echt issue mogen zijn, mits men de 'client' onderhoud. Deze kwetsbaarheid zou alleen echt kunnen bestaan in 'clients' die niet langer onderhouden & getest worden, en het is voor iedereen vanzelfsprekend dat daar nog veel meer risico's aan kleven. 

API versionering zelf, als onderwerp op zich, is zoals al geconcludeerd wordt op basis van een bekende blogpost: kiezen tussen kwaden. 
Ik ben zelf een aanhanger van de header methode omdat de locatie van een resource mijns inziens niets met de versie van de interface te maken heeft, het is technische-context aan het verzoek en daarvoor zijn de headers toch bedoeld. Dat komt overeen met wat @joeribekker  al aanhaalt in zijn quote van de blogpost. Ik zie @CathyDingemanse dat benoemen als 'filosofische overwegingen', persoonlijk zou ik dat eerder 'informatiekundige argumentatie' noemen.
Ik ben zelfs zo brutaal dat ik denk dat de 'versie-header' verplicht zou moeten zijn, liefst zonder defaultwaarde om bewustzijn te forceren. Wel met meta-versienummers voor de nieuwste major, minor en default versie om te uniformeren en faciliteren in uitrol strategie. 
Wil je daarnaast de 'mail een link'-crowd of 'URL-versioning-enthusiasts' ook nog faciliteren kan je verkiezen om het als (query) parameter toe te staan, dit is natuurlijk wel een poldermodel maar software-inhoudelijk is het omgaan met een (query) parameter niet heel anders dan met een header omgaan, en strikt genomen zijn die net als headers een type context bij een URL.

Ik hoop van harte dat dit relaas ook daadwerkelijk wat heeft bijgedragen aan dit issue.

P.S, Ik zou de grote namen overigens zelf niet als voorbeelden zien en volgen zonder echt heel goed te begrijpen waarom ze hun keuzes gemaakt hebben.

**Comment by joostfarla** [comment]
De [hypermedia extensie](https://docs.geostandaarden.nl/api/API-Strategie-ext/#hypermedia), waarin deze zaken zijn verwerkt, is inmiddels vastgesteld. Voor nieuwe punten kan een nieuw issue worden opgevoerd.

**Comment by joeribekker** [comment]
Volgens mij wordt er van alles besproken in de hypermedia extensie die @joostfarla linked BEHALVE het punt uit dit issue. Ik pleit er daarom voor om dit issue te heropenen.

Er wordt over links naar externe assets en navigatie binnen dezelfde API gesproken maar niet hoe bijvoorbeeld een Zaken API moet verwijzen naar een KvK API als een zaak over een bedrijf gaat. Met URLs, unieke sleutels en API locatie hints, gewoon niet?
