### ISSUE TITLE
Principe definities kunnen duidelijker

### ISSUE THREAD

**Issue by jasperroes** [Geonovum/KP-APIs#288]
Opmerking via review-formulier:

Principe definities kunnen duidelijker

Voorgestelde oplossing: Graag de Togaf template aanhouden voor de definitie van principes. https://pubs.opengroup.org/architecture/togaf9-doc/arch/chap20.html#tag_20_03

**Comment by mrtn78** [comment]
gerelateerd aan #309

**Comment by mrtn78** [comment]
Gesloten tijdens werkgroep / TO ADR 25-04-2024
verwerkt in ADR 2
