### ISSUE TITLE
API-10 niet verplichten

### ISSUE THREAD

**Issue by dvh** [Geonovum/KP-APIs#29]
[Resources   ondersteunen "lazy" en "eager" laden van relaties](https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie/principes.md#api-10-resources-ondersteunen-lazy-en-eager-laden-van-relaties)

Dit   is een keuze zijn voor de API-designer. Bovendien hoeft het ondersteunen van   lazy en eager laden zich niet te beperken tot n-op-n relaties. Indien wel   voor dit principe wordt gekozen dan is het gebruik van HAL voor het embedden   van relateerde resources niet verplicht en wordt zelfs afgeraden. HAL is een   dode standaard die nauwelijks ondersteund wordt in de reguliere   programmeeromgevingen van Python, C#, Java, etc. Hal moet geen verplichting   zijn, ook plain json moet bijvoorbeeld mogelijk zijn. In ZDS worden relaties met links gelegd. Eager laden gaat  mogelijk gemaakt worden met de expand query-parameter, maar zonder HAL-syntax in de payload.

Zie ook #6.

**Comment by dvh** [comment]
@HenriKorver volgens mij is het uitgangspunt dat alles uit de NL API Strategie een keuze blijft van de designer en er dus niks 'verplicht' is. Als dat klopt dan hoeven we niets voor dit issue te doen.

**Comment by dvh** [comment]
Dat zou ik ook mooi vinden, maar ik weet niet of het ook zo bedoeld is. @fterpstra kun jij hier iets over zeggen?

**Comment by HenriKorver** [comment]
Ik zou API-10  omdopen tot een best practice (BP-10) en als volgt herformuleren:
_Voor het eager laden van relaties wordt de HAL-standaard aangeraden omdat er vooralsnog geen betere standaard is._

**Comment by jasperroes** [comment]
Heb deze nu optioneel gemaakt, nu een deel nog omnummeren / veranderen naar best practices lukt niet meer. Daarnaast voelt dat ook onlogisch als we eigenlijk principes willen verplichten.
