### ISSUE TITLE
Onderbouwing van sommige regels is onvoldoende of ontbreekt.

### ISSUE THREAD

**Issue by PieterHering** [Geonovum/KP-APIs#309]
Hoewel sommige regels _obvious_ lijken, bijvoorbeeld omdat 'iedereen er mee werkt',  is het vanuit een beheerperspectief raadzaam om alle regels zoveel mogelijk te onderbouwen. We hebben bij het beheer een ander afsprakenset  (Digikoppeling, iets met XML en SOAP )  gemerkt dat wanneer we regels willen aanpassen vanwege nieuwe wensen of voortschrijdend inzicht, vrijwel altijd eerst de motivatie voor de oude regel opzoeken -of proberen te achterhalen. Met motivatie boven water kan de impact van het aanpassen van een regel vaak beter worden ingeschat. 

We missen in ieder geval onderbouwing bij regels: Geonovum/KP-APIs#3, Geonovum/KP-APIs#11, Geonovum/KP-APIs#15, Geonovum/KP-APIs#19, Geonovum/KP-APIs#23, Geonovum/KP-APIs#28, Geonovum/KP-APIs#29, Geonovum/KP-APIs#42, Geonovum/KP-APIs#48, Geonovum/KP-APIs#5 en Geonovum/KP-APIs#49. Over een aantal regels loopt nu nog discussie  Als we eruit zijn, kunnen we dat mooi gebruiken voor een nadere onderbouwing.

Voor aantal van de genoemde regels heb ik een aparte issue aangemaakt.

**Comment by mrtn78** [comment]
Gesloten tijdens werkgroep / TO ADR 25-04-2024
verwerkt in ADR 2
