### ISSUE TITLE
Paginering zonder HAL

### ISSUE THREAD

**Issue by HenriKorver** [Geonovum/KP-APIs#327]
In de sectie [Paginering](https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie/Designrules%20v0.1.md#paginering) van de design rules wordt aangegeven hoe om te gaan met paginering in het geval het mediatype JSON+HAL is. Het zou fijn zijn als we ook weten hoe dat moet in plain JSON. Hieronder een voorstel voor standaardisering van paginering zonder HAL.

```
{
	"count": 100,
	"page_size": 20,
	"self": "https://.../api/registratie/v1/aanvragen?page=3",
	"first": "https://.../api/registratie/v1/aanvragen",
	"prev": "https://.../api/registratie/v1/aanvragen?page=2",
	"next": "https://.../api/registratie/v1/aanvragen?page=4",
	"last": "https://.../api/registratie/v1/aanvragen?page=5",
	results: [
		{
			"self": "https://.../api/registratie/v1/aanvragen/12",
			"titel": "Mijn dakkapel",
			"samenvatting": "Ik wil een dakkapel bouwen!",
			"aanvrager": "Bob"
		},
		...
	]
}
```
De velden `count` en `page_size` geven informatie over het totale aantal resultaten en het aantal dat per pagina wordt teruggegeven. 
De link-namen  `self`, `first`, `prev`, `next` en `last`  zijn gebaseerd op de internetstandaard [RFC5988](https://tools.ietf.org/html/rfc5988) net zoals HAL dat doet.

**Comment by joostfarla** [comment]
De [hypermedia extensie](https://docs.geostandaarden.nl/api/API-Strategie-ext/#hypermedia), waarin deze zaken zijn verwerkt, is inmiddels vastgesteld. Voor nieuwe punten kan een nieuw issue worden opgevoerd.
