### ISSUE TITLE
API-03 verwijzing naar PATCH methode in plaats van formaat?

### ISSUE THREAD

**Issue by kad-baanh** [Geonovum/KP-APIs#349]
Bij API-03 wordt de HTTP PATCH methode uitgelegd met een verwijzing naar rfc5789 (uit 2010). Ook in de bijlage A References staat dit vermeld.

Ik vraag me af wat de toegevoegde waarde hier van is in het kader van de design rules? Alleen de PATCH methode krijgt ook een dergelijke toelichting.

Wat ik mis is de vermelding van het te gebruiken MergePatch formaat bij deze HTTP PATCH, zie https://tools.ietf.org/html/rfc7386. Zou hier over nagedacht kunnen worden?

**Comment by mrtn78** [comment]
de toelichting op patch verplaatsen naar de voetnoot in normatieve regel API-03

MergePatch zou ik eerst als extensie uitwerken. nagaan bij de werkgroep van @HenriKorver wat hierover al onderzocht en beschreven is.

**Comment by mrtn78** [comment]
Dit issue is verwerkt in https://github.com/Logius-standaarden/API-Design-Rules/pull/130 en wordt naar verwachting meegenomen in de volgende release
