### ISSUE TITLE
Forum Standaardisatie verwijst naar verkeerde Design Rules

### ISSUE THREAD

**Issue by ehotting** [Geonovum/KP-APIs#350]
Forum Standaardisatie vermeldt de REST API Design Rules als verplichte standaard. Er wordt echter naar het verkeerde document verwezen.

Op de pagina https://forumstandaardisatie.nl/open-standaarden/rest-api-design-rules staat een link:

<img width="1024" alt="Screenshot 2020-10-10 at 23 37 25" src="https://user-images.githubusercontent.com/20684884/95665536-98dfea80-0b51-11eb-8bbe-9a40cce4fbbc.png">

Deze verwijst naar de 'Versie ter vaststelling 17 januari 2020' op de website van Geonovum:

https://docs.geostandaarden.nl/api/API-Designrules/

Echter de bijbehorende README.md aldaar verwijst naar een andere pagina, waar een 'Vastgestelde versie 17 januari 2020' te vinden is:

https://publicatie.centrumvoorstandaarden.nl/api/API-Designrules/

Interessant is overigens dat de inhoud van beide pagina's aanzienlijk verschillend is, niet alleen qua opmaak maar ook qua inhoud.

Lijkt me goed om e.e.a. recht te trekken, evt. tegelijk met voorstel uit https://github.com/Logius-standaarden/API-Designrules/issues/114

**Comment by kad-baanh** [comment]
Dank je wel Frank. Ik zie dat de links in het begin van het Logius document nu ook aangepast zijn. De _Latest editor's draft_ link geeft overigens nog een 404, maar mogelijk is er nu geen draft ook.

**Comment by jasperroes** [comment]
opgelost.
