### ISSUE TITLE
SemVer & Release tags voor gehele set vastgestelde Design Rules

### ISSUE THREAD

**Issue by ehotting** [Geonovum/KP-APIs#351]
Voorstel:

1. Gebruik voor de standaard 'REST API Design Rules' met Semantic Versioning, waarbij als volgt te werk kan worden gegaan (nader uit te werken):

- Tekstuele wijziging zonder impact, zoals een verduidelijking of wijziging typo: patch
- Toevoegen design rule aan de vastgestelde set: minor
- Wijzigen van een design rule waardoor bestaande eis verandert: major

Aanvullend kan worden gewerkt met bijv. _release candidates_ wanneer een nieuwe versie wordt voorgedragen om vastgesteld te worden.

2. Publiceer release notes

3. Gebruik git release tags voor het markeren en publiceren van een nieuwe versie

---

Door op deze manier te werken kan geen misverstand ontstaan over de versie van de API Design Rules, is voor iedereen duidelijk wanneer een wijziging heeft plaatsgevonden en wat de impact van deze wijziging is.

Ook kunnen de Rules dan extern eenvoudiger worden gebruikt, door rechtstreeks uit de Github Repo te putten uit een specifieke release tag, of de release tag 'latest' oid.

**Comment by mrtn78** [comment]
Gesloten tijdens werkgroep 25-04-2024
