### ISSUE TITLE
Externe URIs als waardes

### ISSUE THREAD

**Issue by dvh** [Geonovum/KP-APIs#352]
Zie https://github.com/Geonovum/KP-APIs/issues/8#issuecomment-431006149.

**Comment by joostfarla** [comment]
De [hypermedia extensie](https://docs.geostandaarden.nl/api/API-Strategie-ext/#hypermedia), waarin deze zaken zijn verwerkt, is inmiddels vastgesteld. Voor nieuwe punten kan een nieuw issue worden opgevoerd.
