### ISSUE TITLE
HTTP status reference

### ISSUE THREAD

**Issue by rschaar-logius** [Geonovum/KP-APIs#356]
The text currently has a broken link explaining HTTP statusses:

> "Always use the semantically appropriate status code for the response."

with a link to https://httpstatuses.com/

That site is currently down (not paying its hoster), and is not authorative. Link RFC 7231, section 6 and friends instead:
https://tools.ietf.org/html/rfc7231#section-6.

**Comment by joostfarla** [comment]
Link aangepast, dank!
