### ISSUE TITLE
a2a?

### ISSUE THREAD

**Issue by rschaar-logius** [Geonovum/KP-APIs#357]
The security extension contains "a2a". As this is the first mention in the API strategy, it would be nice to have it in full as first mention rather than just the abbreviation.

Second, it could mean both application-to-application as "app-to-app" (very subtle difference); the latter would not be applicable given the context where a2a is currently used. Would system-to-system not be more applicable?

**Comment by kad-borgmm** [comment]
I agree to make it system-to-system

**Comment by fterpstra** [comment]
Agreed system to system
