### ISSUE TITLE
editorials

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#36]
- API principes kunnen we markeren als een best practice, dan kun je voorin het doc ook ergens een summary van alle principes zetten. Net zoals in de SDWBP. 
- Hier en daar zie je de DSO bias, niet alleen doordat DSO expliciet genoemd wordt, maar ook in functionaliteit die specifiek in de juridische context van de DSO belangrijjk is. Bv het stuk over tijdreizen. Zoek op ‘juridisch’ en overweeg dit eruit te halen. 
- De stukken voorbeeldcode in een <div class=”example”> zetten.

**Comment by jasperroes** [comment]
Punt 1: ja, goed idee, maar dan moet iemand anders dit toevoegen en moeten we een goede manier hebben om dit te borgen, het heeft nu veel tijd gekost om alle huidige referenties goed te krijgen (ook al omdat respec er anders mee omgaat dan op github).
Punt 2: DSO bias heb ik er zoveel mogelijk uitgehaald, is wel lastig om helemaal te voorkomen omdat de DSO API strategie het uitgangspunt is geweest.
Punt 3: zoveel mogelijk aangepast.
