### ISSUE TITLE
client identifier

### ISSUE THREAD

**Issue by rschaar-logius** [Geonovum/KP-APIs#360]
The section Clients states:
> Authorization servers SHOULD NOT allow clients to choose or influence their client_id value.

1) SHOULD NOT, or MUST NOT?
2) if the client_id value is verifiable or linked to verifiable data (e.g. OIN in PKIo certificate), would that be acceptable (if confidentiality of that information in the use case allows)?

**Comment by kad-borgmm** [comment]
This is text borrowed from te OAuth 2.1 spec.

**Comment by rschaar-logius** [comment]
That does not prevent us from being more strict.

**Comment by kad-borgmm** [comment]
Agreed

**Comment by fterpstra** [comment]
MUST NOT it will be. We do not want clients to choose values that suggest something that is not true. That is a risk we do not want to take
