### ISSUE TITLE
EV PKIo with HRN?

### ISSUE THREAD

**Issue by rschaar-logius** [Geonovum/KP-APIs#361]
mtLS client authn section states:

> Extended Validation certificates (as used for websites) do not include this identifier and are therefore not suitable to use with APIs.

IIRC, EV certififcate can hold the 8-digit KvK-nummer. Check with PKIo?

**Comment by kad-borgmm** [comment]
The PKIo statement is:

> In dit veld MOET het KvK-nummer worden opgenomen. In die gevallen waarbij een organisatorische entiteit binnen de overheid nog niet is ingeschreven in het Handelsregister MOET de TSP zelf het nummer bepalen waarmee de uniciteit van het subject (service) wordt gewaarborgd. Tevens MOET de TSP dan in het veld Subject.organizationalUnitName het woord “overheidsorganisatie” opnemen.

**Comment by rschaar-logius** [comment]
Klinkt als bruikbaar.

**Comment by fterpstra** [comment]
moeten we inderdaad in de tekst aanpassen

**Comment by fterpstra** [comment]
tekst aangepast EV genoemd bij wel bruikbare certificaten
