### ISSUE TITLE
Geen gedetailleerde geometrieën vereisen in brondata

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#38]
In [paragraaf 4.9][1] staat bij	**geo ondersteuning**: 

> het is wel belangrijk dat dit antwoord juist is, en de brondata dus zeer gedetailleerde geometrieën bevat

Dat is echter afhankelijk van de use case en kan je dus in een algemene API strategie niet stellen, zoals gesteld in [Spatial Data on the Web best practice 7][2]. 

Bovendien te simpel gesteld: vaak zal de locatiebepaling van de (gps) device van de vraagsteller niet zo nauwkeurig zijn, en dan helpen gedetailleerde geometrieen niet echt. 

Ik stel voor om deze zin te verwijderen. 

[1]: https://geonovum.github.io/KP-APIs/#geo-ondersteuning
[2]: https://www.w3.org/TR/sdw-bp/#bp-crs-choice

**Comment by jasperroes** [comment]
Verwijderd.
