### ISSUE TITLE
Commentaar van Paul Zeef op het werkdocument Strategie en Beleid

### ISSUE THREAD

**Issue by jzuidweg** [Geonovum/KP-APIs#380]
Paul Zeef gaf het volgende commentaar op het werkdocument Strategie en Beleid:
- **Visie**, laatste zin van de eerste paragraaf: "heeft ook nadelen" is stelliger dan "kan ook nadelen hebben:".
- **Visie**, eerste punt: de bescherming van de privacy van burgers wordt moeilijker.
- **Visie**, laatste zin laatste paragraaf: nu zou je nog een zin verwachte die de paragraaf visie ook als visie afsluit; bijv…de inspanning van de gezamenlijke overheden zal daarom de komende jaren - bij opzet en onderhoud van systemen - consequent gericht moeten worden op dit inrichtingsprincipe.
- **Manifest**, laatste zin: wordt deze passage met het stelseloverleg Basisregistraties op voorhand afgestem/ (Koos Straver/Ronald Slomp/Norbert en Andre v Brussel?.)
- **Stappenplan**: kunnen deze bullets voor bestuurders in iets minder technische termen geformuleerd worden, waarbij de korte formulering tussen haakjes de precisering vormt?
- **API voor zaakgericht werken**: beschrijf vooral wat de API uitwerking hierin voor extra’s biedt!
- **Voorbeeld BRK Publiekrechtelijke beperkingen**, laatste zin derde paragraaf: dit is een beetje vreemde toevoeging in juist deze paragraaf, want gaat niet over de PB-kant uit de titel. Misschien vermelden bij die aansluitingen in volgende alinea?
- **Voorbeeld API voor regie op gegevens**, laatste zin laatste paragraaf: misschien melden dat hier een model API voor bestaat sinds voorjaar 2021 en dat die door gemeenten en andere overheden stapsgewijs in hun data- en applicatielandschap ingepast kan worden (link naar Github).

**Comment by jzuidweg** [comment]
Dank voor je commentaren. Een aantal hiervan heb ik al in het werkdocument verwerkt.

**Comment by Redouan500** [comment]
Feedback is verwerkt. Zie laatste versie van het document: https://github.com/Geonovum/KP-APIs/blob/5dd1031dc7b12df4c2ce8e85c1e6dab5131d63fd/Werkgroep%20API%20strategie%20en%20beleid/Werkversie/api-strategie-overheid.md
