### ISSUE TITLE
Definitie zaak in strategie is onjuist

### ISSUE THREAD

**Issue by MarcoKlerks** [Geonovum/KP-APIs#384]
In de werkversie van de [strategie](https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie%20en%20beleid/Werkversie/api-strategie-overheid.md) staat: _"De meeste gemeenten werken 'zaakgericht'. Deze manier van werken richt zich op het transparant afhandelen van aanvragen die een samenhangende hoeveelheid werk (een 'zaak') met zich meebrengen en een duidelijk omschreven resultaat hebben."_

Het is een veel gemaakte, basale fout dat een zaak altijd getriggerd wordt door een aanvraag. Veel zaken rondom handhaving en toezicht worden bijvoorbeeld niet aangevraagd. Veel organisaties richten ook beleidsvorming, projecten, vergaderingen, et cetera zaakgericht in. En sommige dienstverlening richt de overheid pro-actief in en neemt zij uit eigen beweging contact op met een burger, bijvoorbeeld wanneer zij ziet dat het rijbewijs bijna verlopen is.

Ook de formele [definitie](https://www.gemmaonline.nl/index.php/Rgbz_1.0/doc/objecttype/zaak) omvat niet het woordje "aanvraag".

Tekstvoorstel: "Deze manier van werken richt zich op het transparant afhandelen van _een samenhangende hoeveelheid werk_ (een 'zaak'), welke _een duidelijk omschreven aanleiding_ kent (bijvoorbeeld een aanvraag) en leidt tot _een duidelijk omschreven resultaat_."

**Comment by Redouan500** [comment]
Feedback is verwerkt in het document.
