### ISSUE TITLE
Gebruik van dezelfde gelijke data

### ISSUE THREAD

**Issue by Gerard-arch** [Geonovum/KP-APIs#387]
Wat ik nog mis in de visie is dat we als overheidsorganisaties gebruik maken van dezelfde gelijke data.
Dit zou een extra zinnetje in de visie kunnen zijn. Bijvoorbeeld:
Een belangrijk kenmerk van deze platformen is het gemak en de flexibiliteit waarmee gebruikers diensten kunnen aanbieden en afnemen. Burgers en bedrijven verwachten dit ook van de overheid. **Daarbij mogen zij verwachten dat iedereen binnen de overheid gebruik maakt van dezelfde gelijke data.**

**Comment by Redouan500** [comment]
Feedback is verwerkt in het document.
