### ISSUE TITLE
API Principe 38: GeoJSON niet verplicht stellen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#39]
[API principe 38][1] stelt GeoJSON verplicht als formaat. 

Hoewel ik het daar in de meeste gevallen helemaal mee eens ben, zijn er helaas situaties waarin GeoJSON niet voldoet. Het ondersteunt bijvoorbeeld niet alle geometrietypen die we mogelijk willen serveren, bijvoorbeeld geen solids en dus geen 3D data. 

Ik stel voor om dit te nuanceren (bv toevoegen: tenzij GeoJSON ontoereikend is voor de data die je wilt serveren, zoals…).  

[1]: https://geonovum.github.io/KP-APIs/#api-38-geo-api-s-ontvangen-en-versturen-geojson

**Comment by jasperroes** [comment]
GeoJSON is nu de voorkeur geworden, geen verplichting meer.
