### ISSUE TITLE
Werkdocument: platformeconomie vervangen door platformen

### ISSUE THREAD

**Issue by marcelkrassenburg** [Geonovum/KP-APIs#393]
In de visie en de samenvatting wordt platform**economie** gebruikt. Ik denk dat we dat economiedeel voor de overheid juist niet willen ... Wel de open en flexibele manier van gegevensgebruik van platformen. Tekstvoorstel: platformeconomie vervangen door platformen.

In de laatste sessie spraken we ook over ecosystemen. Dat is niet meer uitgewerkt en gezien de tijdsdruk moeten we dat maar laten. Voor begrip van het belang van API's is het platformconcept ook heel werkbaar.

**Comment by Redouan500** [comment]
Dank voor je input!

**Comment by Redouan500** [comment]
Feedback is besproken, en het we hebben gekeken naar mogelijk afweging tussen "platformeconomie" en "platformen". De discussie over die termen kun je hier treffen: https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie%20en%20beleid/Verslagen/Verslag%2020210629%20WG%20Strategie%20en%20Beleid.md
