### ISSUE TITLE
Coördinatenstelsel-conversie

### ISSUE THREAD

**Issue by HenriKorver** [Geonovum/KP-APIs#4]
Principes API-43 t/m API-45 uit de DSO API Strategie gaan over coördinatenstelsels en mogelijke transformaties. Waar wordt de coördinatenstelsel-conversie gedaan? Client? Service? Moet elke service dat zelf doen ? Kan conversie niet als een externe service aangeroepen worden zodat clients/services simpel blijven?

**Comment by jasperroes** [comment]
Voorstel vanuit de werkgroep:
Principes API-39 t/m API-41 zo aanpassen dat de client niet verplicht is om een coordinaatstelsel mee te geven maar dat de API verplicht een default kent. Response bevat wel verplicht het coordinaatstelsel. 

Wel verplichting om content negotiation aan te bieden (je moet als provider altijd accept-crs ondersteunen).

Hierbij ook de tekst in de strategie aanpassen.

**Comment by lvdbrink** [comment]
https://www.w3.org/TR/sdw-bp/#CRS-background

**Comment by mevdschee** [comment]
>De Nederlandse overheid biedt vaak RD aan, waar de rest van de wereld WGS84 (of ETRS89, dat verschil is verwaarloosbaar) verwacht.

Ik lees echter:

>Note that the World Geodetic System WGS84 and the European Reference System ETRS89 are virtually identical and that coordinate transformation between the two systems in practical navigation is unnecessary. However, for high-precision surveying work - be aware that the two systems deviates more than half a meter.

https://www.engineeringtoolbox.com/utm-latitude-longitude-d_1370.html

Okay, voor voertuignavigatie zijn ze verwaarloosbaar, maar voor het intekenen van lantaarnpalen door de gemeente lijkt me dit toch een probleem. Of zie ik iets over het hoofd?

**Comment by dvh** [comment]
Nee, daar heb je gelijk in. Maar als de NL API Strategie zich met name richt op "de webdeveloper die leuke innovatieve webapplicaties moet kunnen maken" (een van mijn feedbackpunten is overigens dat dat niet helemaal duidelijk naar voren komt in de API Strategie, óf dat zo is of niet) is dit goed te verantwoorden. Immers zal een gemeente hoogstwaarschijnlijk lantaarnpalen gaan intekenen met gespecialiseerde GIS pakketten. Dat gaat niet alleen over het CRS, dat gaat ook over de rechtsgeldigheid van de data zelf, de precisie, het zoomniveau, etc. En dan hebben we nog de complexe geo operaties met intersects, disjoints, etc.

**Comment by lvdbrink** [comment]
Hier ook nog wat input over dit onderwerp, vanuit INSPIRE. 

> As per the requirements of the GeoJSON - IETF RFC 7946 specification, the default CRS for any data set delivered using this encoding rule is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) datum, with longitude and latitude units of decimal degrees, unless there is prior arrangement. This is equivalent to the coordinate reference system identified by the Open Geospatial Consortium (OGC) URN urn:ogc:def:crs:OGC::CRS84.

>NOTE As INSPIRE mandates the use of the European Terrestrial Reference System 1989 (ETRS89, see Requirement 1) for the areas within the geographical scope of ETRS89 and both CRS84 and ETRS89 use the GRS 80 ellipsoid (although with minor enhancements), we shall assume CRS84 to be equivalent to ETRS89. If, for any dataset, this assumption would be problematic, then GeoJSON cannot serve as an alternative encoding rule for that dataset.

Bron: [INSPIRE GeoJSON encoding rule, sectie over Coordinate Reference Systems](https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md#coordinate-reference-systems)

**Comment by inoorhoff** [comment]
Het moet mogelijk blijven dat de leuke innovatieve webapplicaties mutaties leveren van objecten die in RD beschreven zijn. Omdat coördinaat transformaties altijd verschillen opleveren moet het mogelijk zijn om aan de authentieke geometrie te komen in originele coördinaat stelsel.

**Comment by jasperroes** [comment]
Opgelost.
