### ISSUE TITLE
Ruimtelijke operators

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#40]
In [paragraaf 4.9][1] worden drie ruimtelijke operators genoemd die ondersteund moeten worden: within, contains, en intersects. 
 
De [SDWBP noemt meer ruimtelijke operators][2]. Naast de drie al genoemde zijn dit `Equals`, `Disjoint`, `Touches`, `Crosses`. We kunnen een link naar de SDWBP opnemen hiervoor, dan hoeven we ze niet allemaal te noemen. 

Ik zou niet zeggen dat die ondersteund moeten worden maar wel: als je ze ondersteunt, noem ze dan zo. 

[1]: https://geonovum.github.io/KP-APIs/#geo-ondersteuning
[2]: https://www.w3.org/TR/sdw-bp/#entity-level-links

**Comment by jasperroes** [comment]
Verwijzing opgenomen.
