### ISSUE TITLE
geojson als formaat of als ontologie

### ISSUE THREAD

**Issue by pvgenuchten** [Geonovum/KP-APIs#424]
er wordt gesproken over geojson output, echter er wordt niet duidelijk gemaakt of dit in de context van het geojson formaat [rfc](https://datatracker.ietf.org/doc/html/rfc7946), dan wel de [geojson ontologie](https://geojson.org/geojson-ld). Beide zijn interessant om te ondersteunen, maar dient wel expliciet gemaakt te worden.

- outputformat application/geo+json geeft een document terug volgens de rfc (blob) net als bv het geopackage outputformaat
- voor het embedden van geometrie in bestaande open-api-json kun je de geojson ontologie gebruiken

**Comment by lvdbrink** [comment]
Vragen voor JSON-FG SWG: 
- onderschrijven ze het idee van geojson als ontologie? Waarbij je bv een json-fg geometrie kan stoppen in een JSON structuur?
- gaan ze een JSON Schema maken?

**Comment by lvdbrink** [comment]
> gaan ze een JSON Schema maken?

Ja, dit is onderdeel van het werk dat gedaan wordt. Er zijn al draft schemas: 
https://github.com/opengeospatial/ogc-feat-geo-json/tree/main/core/schemas

**Comment by lvdbrink** [comment]
> onderschrijven ze het idee van geojson als ontologie? Waarbij je bv een json-fg geometrie kan stoppen in een JSON structuur?

JSON-LD support is future work: https://github.com/opengeospatial/ogcapi-features/issues/167

In de spec staat verder het volgende bij [Requirements class GeoJSON](http://docs.ogc.org/is/17-069r3/17-069r3.html#_requirements_class_geojson):
> Every 200-response with the media type application/geo+json SHALL be

> - a [GeoJSON FeatureCollection Object](https://tools.ietf.org/html/rfc7946#section-3.3) for features, and

> - a [GeoJSON Feature Object](https://tools.ietf.org/html/rfc7946#section-3.2) for a single feature.

D.w.z. hier spreken ze over het GeoJSON formaat als in IETF RFC 7946. Naar deze standaard wordt ook gerefereerd in de [References sectie](http://docs.ogc.org/is/17-069r3/17-069r3.html#_references).

**Comment by lvdbrink** [comment]
Voor het gebruik van GeoJSON als ontologie bestaan al conventies en de JSON-FG groep denkt ook in deze richting. 

Zie vb https://gist.github.com/codan-telcikt/e1d59ccc9a3af83e083f1a514c84026c

JSON-FG is nog een draft. We kunnen op een later tijdstip overwegen hun schema over te nemen en eventueel uit te breiden. 

Issue openen over gebruik van andere formaten dan GeoJSON in API's.
