### ISSUE TITLE
Is het gebruik van HTTP status code 406 bij CRS negotiation strijdig met RFC 7231?

### ISSUE THREAD

**Issue by strijm** [Geonovum/KP-APIs#427]
De status code 406 Not Acceptable heeft volgens [RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-6.5.6) betrekking op de headers:

-	Accept
- 	Accept-Charset
-	Accept-Encoding
-	Accept-Language

Accept-Crs staat daar niet bij. Mag de status code 406 gebruikt worden voor de CRS negotiation header Accept-Crs?

Aanleiding van de vraag is dat er bij een programma een besluit is genomen, dat status code 415 *Unsupported Media Type) niet gebruikt mag worden voor Content-Crs, omdat deze status code alleen bij Content-Type en Content-Encoding gebruikt mag worden volgens RFC 7231.

Als de 415 status code alleen voor Content-Type en Content-Encoding gebruikt mag worden volgens de RFC 7231, mag de status code 406 dan ook alleen voor de genoemde headers worden gebruikt en niet voor CRS negotiation headers? Welke status codes moeten er dan gebruikt worden?

Ik wil voorstellen om in de CRS negotiation paragraaf alle mogelijke scenario's op te nemen en de te gebruiken status codes in ieder scenario te benoemen.

**Comment by lvdbrink** [comment]
Dit issue is niet relevant meer omdat we de OGC API Features methode voor omgaan met CRS via parameters overnemen en de CRS conneg methode deprecated verklaren.
