### ISSUE TITLE
GeoJSON is niet geschikt voor BGT data

### ISSUE THREAD

**Issue by sweco-nlgemo** [Geonovum/KP-APIs#429]
`API-34` stelt GeoJSON voor als formaat/ontologie voor geometrieen. De GeoJSON standaard [RFC7946](https://www.rfc-editor.org/rfc/rfc7946.txt) schrijft voor dat lineaire interpolatie tussen punten toegepast moet worden, waardoor het onmogelijk is om bogen (en cirkels) in GeoJSON te encoderen.. 

Door deze randvoorwaarde is het niet mogelijk om API regel `API-34` toe te passen op BGT data, omdat in deze geo-standaard bogen toegestaan zijn en in de praktijk ook daadwerkelijk voorkomen.

Als de API design rules ook op BGT data van toepassing zijn dan is een ander formaat voor geometrieen nodig.

**Comment by sweco-nlgemo** [comment]
Vanuit OGC wordt gewerkt aan de [OGC Features and Geometries JSON](https://www.ogc.org/projects/groups/featgeojsonswg) (*JSON-FG*) standaard wat een aantal beperkingen van GeoJSON moet oplossen. Mogelijk is deze standaard een goede vervanger voor GeoJSON.

Ik heb op de GitHub van dit project een issue aangemaakt om aandacht te vragen voor bogen en cirkels: [Issue 35](https://github.com/opengeospatial/ogc-feat-geo-json/issues/35)

**Comment by lvdbrink** [comment]
Aanvullen met informatie over operationeel gebruik in NL + databases en bibliotheken met ondersteuning voor cirkelbogen.

**Comment by sweco-nlgemo** [comment]
Operationeel gebruik:
* Basisregistratie Grootschalige Topografie (BGT)
* NLCS (Nederlandse CAD Standaard)

Databases:
* Oracle
* PostgreSQL met PostGIS extensie
* GeoPackage (via extensie)

Clients:
* QGis
* CAD applicaties (AutoCAD, Microstation, ...)
* BGT applicaties (dg DIALOG BGT, NedBGT, ...)
* FME
* ArcGIS

**Comment by sweco-nlgemo** [comment]
Voor JSON-FG heb ik inmiddels een voorstel gemaakt voor de ondersteuning van bogen en cirkels (https://github.com/opengeospatial/ogc-feat-geo-json/pull/43), de OGC werkgroep gaat dit hopelijk binnenkort bespreken.

**Comment by lvdbrink** [comment]
Er is zoals @sweco-nlgemo zegt een voorstel voor het toevoegen van bogen en cirkels in JSON-FG. Dit voorstel is op de backlog van de JSON-FG werkgroep opgenomen, maar zal pas worden opgepakt nadat het schrijfwerk aan v0.1 van de core JSON-FG standaard gereed is. Waarschijnlijk komt de toevoeging van bogen en cirkels niet in JSON-FG Core maar in een extension. 

Vraag die ons rest: wat zetten we in de geo-extensie zolang het niet zover is? 

**Voorstel:** een Note opnemen waarin we schrijven dat JSON-FG er aan komt met de toekomstige uitbreiding daarvan met bogen/circels; en zo mogelijk een workaround voor zolang het nog niet zover is. 

Misschien als workaround: stroken? Zie ook https://stackoverflow.com/questions/16942697/geojson-circles-supported-or-not. 

Andere workaround ideeën welkom.

**Comment by lvdbrink** [comment]
7-6-2022: Zie #438

**Comment by lvdbrink** [comment]
21-6: kan gesloten worden. Voorstel voor bogen in JSON-FG is geland bij OGC en alternatieven voor GeoJSON zijn in de tekst van de geo-extensie benoemd.
