### ISSUE TITLE
Formaat van waardes voor HTTP headers Content-Crs en Accept-Crs

### ISSUE THREAD

**Issue by sweco-nlgemo** [Geonovum/KP-APIs#431]
In de paragraaf *CRS negotiation* staan deze tabellen met mogelijke waardes voor de HTTP headers *Content-Crs* en *Accept-Crs*:

|HTTP header|Value|Explanation|
|-|-|-|
|`Content-Crs`|EPSG:4326|WGS84, global|
|`Content-Crs`|EPSG:3857|Web Mecator, global|
|`Content-Crs`|EPSG:4258|ETRS89, European|
|`Content-Crs`|EPSG:28992|RD/Amersfoort, Dutch|

|HTTP header|Value|Explanation|
|-|-|-|
|`Accept-Crs`|EPSG:4326|WGS84, global|
|`Accept-Crs`|EPSG:3857|Web Mercator, global|
|`Accept-Crs`|EPSG:4258|ETRS89, European|
|`Accept-Crs`|EPSG:28992|RD/Amersfoort, Dutch|

Bij beide headers is de waarde in de vorm **EPSG:xxx**.

In de standaard [OGC API - Features - Part 2: Coordinate Reference Systems by Reference](https://github.com/opengeospatial/ogcapi-features/tree/master/extensions/crs) wordt geschreven dat een CRS in de vorm van een URI moet worden opgegeven: `Each supported CRS must be identified by a URI such as http://www.opengis.net/def/crs/EPSG/0/4326.`

Er wordt ook een voorbeeld gegeven met een waarde voor de header *Content-Crs*:

```
$ curl -i "https://example.com/api/v1/collections/buildings/items/1?crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F25832"

HTTP/1.1 200 OK
Date: Sun, 24 May 2020 15:30:56 GMT
Content-Type: application/geo+json
Content-Language: en
Content-Crs: <http://www.opengis.net/def/crs/EPSG/0/25832>
Vary: Accept-Language,Accept-Encoding
Content-Length: 1064
```

Als compatibiliteit met de OGC standaarden gewenst is dan zouden de waardes aangepast kunnen worden naar URI's.

**Comment by lvdbrink** [comment]
Deze is niet meer relevant want we hebben besloten de 'oude' CRS opvraagmethode uit te faseren en tot die tijd ongemoeid te laten.
