### ISSUE TITLE
Voeg regel toe: Provide a list of all CRSs that are supported by the API.

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#433]
**API-xx**: Provide a list of all CRSs that are supported by the API.

The crs property in the collection object of a spatial feature collection shall contain the identifiers for the list of CRSs supported by the server for that collection.

(bron: OGC API Features part 2 CRS)

**Comment by lvdbrink** [comment]
Op basis van https://docs.ogc.org/is/18-058/18-058.html#_crs_identifier_list

**Comment by PB-GNM** [comment]
Mark komt met voorstel met 3 niveaus (api, collection en feature) conform OGC part 2 specs.
Ook aandacht voor geval er geen coördinaten in de service terug gegeven worden.
