### ISSUE TITLE
Verkeerde tekst in API-41

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#439]
Tijdens het editen van de CRS negotiation regels is de tekst in [12.4 CRS Transformation](https://geonovum.github.io/KP-APIs/API-strategie-extensies/#crs-transformation) per ongeluk vervangen door oude tekst uit een andere API design rule. Dit moet hersteld worden.

**Comment by PB-GNM** [comment]
Moet inderdaad aangepast worden.
