### ISSUE TITLE
link "Latest editor's draft" in https://docs.geostandaarden.nl/api/API-Strategie-ext/ klopt niet

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#441]
De link "Latest editor's draft" in https://docs.geostandaarden.nl/api/API-Strategie-ext/ verwijst naar https://geonovum.github.io/KP-APIs/  ipv naar https://geonovum.github.io/KP-APIs/API-strategie-extensies/

**Comment by joostfarla** [comment]
Fixed!
