### ISSUE TITLE
Voeg toelichting toe over CRS systemen anders dan WGS84 in combinatie met GeoJSON

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#442]
Op basis van mail van @HenriKorver: 

Ik dacht dat WGS84 het enige CSR-systeem is wat je voor GeoJSON mag gebruiken, zie: 

https://datatracker.ietf.org/doc/html/rfc7946#section-4

Hoe kan het dan dat in de extensions van de landelijke design rules toch andere CRS-systemen worden toegelaten?

M.a.w. API-39 lijkt te conflicteren met onderstaande design rules API-34 en API-35…

**Comment by lvdbrink** [comment]
In GeoJSON mag je inderdaad eigenlijk alleen WGS84 gebruiken, maar er is een soort escape beschreven (in GeoJSON IETF) dat je een ander CRS mag gebruiken, mits dit in een afspraak met de afnemers van de data geregeld is. 

De API functionaliteit om via een client een ander CRS te vragen en te ontvangen kun je zien als zo’n afspraak. 

Ook is er in de CRS handreiking van Geonovum beschreven waarom je in de praktijk ETRS89 gelijk kunt stellen aan WGS84 onder bepaalde omstandigheden. https://docs.geostandaarden.nl/crs/cv-hr-crs-20211125/#wgs-84-gelijkstellen-aan-etrs89

Ideaal is dit niet, daarom is de OGC bezig met een extensie op GeoJSON, JSON Features and Geometries (JSON-FG)  waarin je wel andere CRS systemen mag gebruiken (waarbij gezorgd wordt dat de data volledig GeoJSON compatible blijft). Maar dit is nog net niet ver genoeg om nu in de geo-extensie op te nemen. https://github.com/opengeospatial/ogc-feat-geo-json

Op basis van bovenstaande toelichting een uitleg in de geo-extensie opnemen over CRS en GeoJSON (in een Noot).

**Comment by strijm** [comment]
Dit issue is volgens mij al opgelost door PR #452.

**Comment by PB-GNM** [comment]
Ik mis in #452 toch nog wel de toevoeging van Linda over gebruik van andere CRS-en dan WGS84 in GeoJSON.
in Part 2 van de specificatie van OGC-API Features staat hierover een [Requirement 14](http://docs.opengeospatial.org/is/18-058/18-058.html#_features_and_feature_resources) en die verwijst op zijn beurt naar:  https://tools.ietf.org/html/rfc7946#section-4
