### ISSUE TITLE
API-39. Waarom staat daar alleen EPSG89 en niet ook RD?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#446]
In de geo-extensie staat:

API-39: Use ETRS89 as the preferred coordinate reference system (CRS)

Waarom staat daar alleen EPSG89 en niet ook RD zoals ook veel gebruikt wordt in Nederland? Zie ook [handreiking voor het gebruik van CRS-en](https://docs.geostandaarden.nl/crs/crs/)

**Comment by lvdbrink** [comment]
Voorstel Pieter: verwijs naar de handreiking en volg die. 

Liefst met een regel dat je moet aangeven welk CRS de default is. Dit is afhankelijk van #425 wat betreft de onduidelijkheid over default CRS in OGC API Features. 

En met een aanbeveling om ook CRS84 conform OGC API Features aan te bieden.

**Comment by PB-GNM** [comment]
Mijn voorstel:
Blauwe deel:

![image](https://user-images.githubusercontent.com/80040145/173367827-20abc22a-0b4b-4b75-b266-3014a71912df.png)

vervangen door:

API-40: Use ETRS89 and/or RD as one of the preferred coordinate reference system (CRS). Follow the [Dutch Guideline for the use of CRSs] (https://docs.geostandaarden.nl/crs/cv-hr-crs-20211125/).

General usage of the European ETRS89 coordinate reference system (CRS) or RD/NAP is preferred, but not the default CRS. Hence, one of these CRSs has to be explicitly included in each request when one of these CRSs is desired in the response or used in a request.

**Comment by PB-GNM** [comment]
Dat je WGS84 ook moet aanbieden en dat dat de default is staat al in de tekst er boven.

**Comment by lvdbrink** [comment]
21-6: we nemen het tekstvoorstel van Pieter over.
