### ISSUE TITLE
mis nog verwijzing naar Part 2 net als die naar Part 1 er wel in zit.

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#455]
Voor part 1 staat er een normatieve verwijzing voor bijlage A1:
},
    "ogcapi-features-1": {
      href: "http://docs.ogc.org/is/17-069r3/17-069r3.html",
      title: "OGC API - Features - Part 1: Core",
      editors: ["Clemens Portele", "Panagiotis (Peter) A. Vretanos", "Charles Heazel"],
      status: "Approved",
      publisher: "Open Geospatial Consortium",
    }

Dit zouden we ook voor Part 2 er in kunnen zetten, dus 

},
    "ogcapi-features-2": {
      href: "http://docs.ogc.org/is/18-058/18-058.html",
      title: "OGC API - Features - Part 2: Coordinate Reference Systems by Reference",
      editors: ["Clemens Portele", "Panagiotis (Peter) A. Vretanos"],
      status: "Approved",
      publisher: "Open Geospatial Consortium",
    }

**Comment by lvdbrink** [comment]
Issue had gesloten moeten zijn, zie commit https://github.com/Geonovum/KP-APIs/commit/2b6fc2a1ebf7b3d0223d39f401247229b6c43c8a en commit https://github.com/Geonovum/KP-APIs/commit/fed0f545a0b27d25154f1ba9e1c62dad24531e12.
