### ISSUE TITLE
Coordinate order lat-long moet volgens OGC API features Part 1 long-lat zijn

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#457]
in 12.4 CRS negotiation staat: 
**The default CRS (Coordinate Reference System) for GeoJSON and for OGC API Features is WGS84 with coordinate order lat-long, also referred to as "CRS84"**
in [OGC API features Part 1](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html) staat:
**WGS 84 with axis order longitude/latitude**

Ik denk dat we ons moeten aanpassen aan de laatste. Dus eerste lengte (van west naar oost en dan breedte van zuid naar noord).
Dat betekent ook dat we onze voorbeelden moeten aanpassen:
Paleis Soestdijk is dan met WGS coördinaten (5.28, 52.19)
en de bbox voor de panden wordt dan bv bbox=5.2,52.1,5.3,52.2

**Comment by lvdbrink** [comment]
Opgelost in #459
