### ISSUE TITLE
Gebruik van SemVer in de API Design Rules

### ISSUE THREAD

**Issue by dnperfors** [Geonovum/KP-APIs#463]
In de [API Design Rules](https://publicatie.centrumvoorstandaarden.nl/api/adr/#versioning) staat bij API-56 dat SemVer gebruikt moet worden en dat de major, minor en patch gebruikt moeten worden.
Laat ik voorop stellen dat het inderdaad belangrijk is om geen breaking changes te hebben in een API, maar ik vraag me af in hoeverre het gebruik van alle 3 de velden te verklaren is.

De major versie geeft aan dat er breaking changes zijn, dus die hoort er te zijn.
De minor versie geeft aan dat er toevoegingen zijn op de API, zoals extra velden in een model.
Maar voor patch zie ik op een API niveau geen enkele reden.

Graag zou ik dan ook zien dat API-56 wordt aangepast naar het volgende:
> API-56: Adhere to the Semantic Versioning model when releasing API changes

> 
> Version numbering must follow the Semantic Versioning [[SemVer](https://publicatie.centrumvoorstandaarden.nl/api/adr/#bib-semver)] model to prevent breaking changes when releasing new API versions. Versions are formatted using the `major.minor` template. When releasing a new version which contains backwards-incompatible changes, a new major version must be released. Minor releases may only contain backwards compatible changes (e.g. the addition of an endpoint or an optional attribute).
> The use of patch releases (and thus the `major.minor.patch` template) is optional

**Comment by mrtn78** [comment]
Reden voor een patch kunnen aanpassingen in de OAS file zijn waarbij wellicht alleen voorbeelden of tekstuele verbeteringen zijn doorgevoerd. We houden dan ook vast aan de huidige Semver standaard.
