### ISSUE TITLE
API Strategie publicatie verbeteren

### ISSUE THREAD

**Issue by adgerrits** [Geonovum/KP-APIs#470]
Publicatie van de API-strategie is niet consistent en lastig. 

Ik vind nu via verschillende paden en zoekmachine bijv. zowel:

- https://docs.geostandaarden.nl/api/API-Strategie/ (vastgesteld 9-3-2022), als
- https://geonovum.github.io/KP-APIs/API-strategie-algemeen/ (vastgesteld 23-9-2022) 
en werd op het verkeerde been gezet omdat ik niet doorhad dat de eerste een werkversie was...

Zou fijn zijn als je net als https://publicatie.centrumvoorstandaarden.nl/api/adr/ ook de API-strategie en Extensies 1 wat makkelijker vindt. Is nu altijd een beetje zoeken. https://www.geonovum.nl/themas/kennisplatform-apis kan, maar moet je ook maar net kennen. Misschien een aparte website (nlapistrategie.nl is nog vrij...) of zo?

**Comment by fterpstra** [comment]
Dit staat zeker op ons netvlies. We willen toe naar een centrale duidelijk herkenbare plek waar de standaarden te vinden zijn. Vrijdag presenteren bij onze bijeenkomst een voorstel hiervoor.

**Comment by fterpstra** [comment]
publicatie is sinds indienen van het issue verbeterd blijft wel een constant aandachtspunt
