### ISSUE TITLE
Geo module test op API GEO-10 en GEO-12

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#472]
**Test op API GEO-10:**
Als een API posten niet ondersteunt kan je dit niet testen, terwijl het volgens mij niet verplicht is het posten te ondersteunen. Dus misschien moet er iets bij als "When HTTP POST requests are supported, than... ".

**Test op API GEO-12:**
Zelfde opmerking als bij API GEO-10, maar ook nog dat er in de test staat "using the crs parameter"  terwijl er in de eis staat "using a header". Ik neem aan dat het in de test ook "using a header" moet zijn.

**Comment by lvdbrink** [comment]
> Test op API GEO-10:
> Als een API posten niet ondersteunt kan je dit niet testen, terwijl het volgens mij niet verplicht is het posten te ondersteunen. Dus misschien moet er iets bij als "When HTTP POST requests are supported, than... ".

Ik zal dit toevoegen en ook een extra zin vóór API-GEO-10 om duidelijk te maken dat dit over transacties / POST requests gaat. 

> Test op API GEO-12:
> Zelfde opmerking als bij API GEO-10, maar ook nog dat er in de test staat "using the crs parameter" terwijl er in de eis staat "using a header". Ik neem aan dat het in de test ook "using a header" moet zijn.

Volgens mij klopt API-GEO-12 wel. Hier gaat het erom, dat wanneer geodata wordt opgevraagd, de **server in de header moet aangeven, met `Content-crs`, wat het CRS in de response is**. Om dit te testen moet je geodata opvragen in een bepaald crs, en hiervoor gebruik je de `crs` parameter....
