### ISSUE TITLE
Tekstuele verbeteringen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#475]
- [x] Hoofdstuk 1 Introductie: tekstueel: "a bit more" is informeel -> "more"
- [x] Hoofdstuk 1 Introductie: tekstueel: woord "specific" wordt te vaak gebruikt
- [x] Gehele tekst: De officiële naam is niet "WGS84", maar "WGS 84".
- [x] Gehele tekst: "ETRS89 (EPSG:4258)" is een onnauwkeurige ensemblecode, het is beter om uitsluitend "ETRF2000 (EPSG:9067)" te gebruiken.
- [x] Gehele tekst: "Amersfoort" is geen onderdeel van de officiële naam van het "Stelsel van de Rijksdriehoeksmeting" (RD). Consistente naamgeving door het hele document, als er verwezen wordt naar EPSG namen, dit expliciet benoemen.
- [x] Ik mis het gebruik van [RFC 2119](https://www.ietf.org/rfc/rfc2119) voor keywords als MAY, MUST, SHOULD etc.
- [x] Onduidelijk welk gedeelte van deze tekst normatief is en welk gedeelte enkel informatief is.
- [x] Tekst is in het Engels, maar veel voorbeelden hebben Nederlandse termen. Waarom niet alles in het Engels? Dat maakt het geheel veel leesbaarder. bijv. `api/v1/buildings` ipv `api/v1/panden`
- [x] "To do" verwijderen
- [x] WGS 84 wordt soms gebruikt waar expliciet CRS84 bedoeld wordt. Of overal WGS84 vervangen door CRS84 waar CRS84 wordt bedoeld. Waar WGS 84 pseudo mercator staat mag wel WGS 84 blijven staan.

Na verwerking van de opmerkingen graag nog een keer laten reviewen o.a. door Kadaster.

**Comment by lvdbrink** [comment]
> Na verwerking van de opmerkingen graag nog een keer laten reviewen o.a. door Kadaster.
Dit zullen we zeker doen, met name wat betreft de punten rondom coördinaatreferentiesystemen. Onze intentie is om goed aan te sluiten op zowel de OGC standaarden als de [handreiking CRS](https://docs.geostandaarden.nl/crs/crs/) en daarbij is een laatste review door de experts van het Kadaster gewenst.

**Comment by lvdbrink** [comment]
@strijm het enige wat ik nog kon vinden is 2x "Amersfoort" in de tabel met CRS URIs. Ik weet niet of je dat over het hoofd had gezien of expres had laten staan. Misschien is het daar ook wel op z'n plek zodat mensen die het onder die naam kennen / zoeken het ook kunnen vinden.

**Comment by strijm** [comment]
@lvdbrink die heb ik idd. bewust laten staan, omdat dat de naam is die in de EPSG specificatie staat.

**Comment by lvdbrink** [comment]
Top, dan kunnen we deze nu afsluiten!
