### ISSUE TITLE
Informatie toevoegen over GeoJSON alternatieven bij gebruik van arcs

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#476]
Commentaar uit consultatie oktober 2022: 

> Er worden alternatieven genoemd voor GeoJSON bij het gebruik van arcs. Ik zou dan ook informatie verwachten over hoe die alternatieven geëmbed moeten worden in de JSON. Voor GML lijkt me die als string opnemen niet heel wenselijk, maar het hele bericht GML maken ook niet. Is er ook gekeken naar TopoJSON als alternatief (ook geen OGC-standaard, maar JSON-FG ook nog niet officieel)?

**Comment by strijm** [comment]
Arcs (of andere geometrieën die niet in GeoJSON worden ondersteund) kunnen als een WKT of WKB string in JSON worden opgenomen en Content-Type: application/json. 
Als er alleen geometrie wordt uitgewisseld kan WKT of WKB worden uitgewisseld met Content-Type: text/plain en GeoJSON met Content-Type application/geo+json.

**Comment by sweco-nlgemo** [comment]
Opgelost middels PR #568
