### ISSUE TITLE
WGS84 lat-long moet long-lat zijn

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#477]
In het stukje:

> Officially, WGS84 lat-long (CRS84) is the only CRS allowed in GeoJSON. However, GeoJSON does state that using another CRS is allowed, if this is agreed between provider and consumer of the data. The API functionality described above, to negotiate the CRS between client and server, can be viewed as such an agreement.

moet het denk ik WGS84 long-lat zijn.

(gemeld tijdens consultatie okt 2022)

**Comment by sweco-nlgemo** [comment]
[RFC7946](https://www.rfc-editor.org/rfc/rfc7946) noemt dit in paragraaf [3.1.1](https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1) inderdaad:

*A position is an array of numbers.  There MUST be two or more
   elements.  The first two elements are longitude and latitude, or
   easting and northing, precisely in that order and using decimal
   numbers.  Altitude or elevation MAY be included as an optional third
   element.*

**Comment by sweco-nlgemo** [comment]
De daarop volgende alinea meldt dit:

*In addition, the Geonovum CRS guidelines [[hr-crs]] describe [how ETRS89 can be treated as equal to WGS84 under certain circumstances](https://docs.geostandaarden.nl/crs/cv-hr-crs-20211125/#wgs-84-gelijkstellen-aan-etrs89) - but note that GeoJSON requires coordinates to be in latitude-longitude order, while ETRS89 uses longitude-latitude.*

Het stuk tekst * - but note that GeoJSON requires coordinates to be in latitude-longitude order, while ETRS89 uses longitude-latitude.* kan dan weg volgens mij. Klopt dat @lvdbrink ?

**Comment by lvdbrink** [comment]
Ja, klopt.

( :-( gaat zo vaak mis met die coordinaatvolgorde)
