### ISSUE TITLE
Link naar INSPIRE requirements is gebroken

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#480]
Er wordt gelinkt naar https://github.com/INSPIRE-MIF/gp-ogc-api-features/blob/master/spec/oapif-inspire-download.md#83-requirements-class-inspire-oapif-geojson-, maar de link daarin naar de requirements class is dood.

NB dit is een gebroken link in een ander document dan de geo module zelf.

**Comment by PB-GNM** [comment]
Omdat dit niet om de link zelf gaat maar om een onderliggende link, denk ik dat wij hier niets aan kunnen veranderen.
Voor zover ik weet zijn er geen betere links dan deze. Op de site waar dit issue speelt heb ik wel een issue aangemaakt.
https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/86
Ik stel voor dat we deze call sluiten, omdat we er nu verder niets aan kunnen doen.

**Comment by strijm** [comment]
Link vervangen door: https://inspire-mif.github.io/gp-ogc-api-features/spec/oapif-inspire-download.html#req-oapif-json
