### ISSUE TITLE
Methode voor omgaan met meerdere geo operators ontbreekt

### ISSUE THREAD

**Issue by strijm** [Geonovum/KP-APIs#484]
12. par 2.2: De oude extensie had wel een methode voor het omgaan met meer operators, en complexe geometrieën. Deze wordt ook veelvuldig gebruikt binnen het Kadaster en het DSO. Als dat nu helemaal wordt weggelaten, is er geen enkele standaard meer om te implementeren? Voorbeelden uit oude versie als deprecated opnemen of in appendix?

**Comment by lvdbrink** [comment]
Besproken in wg: we nemen de voorbeelden op in een bijlage met daarbij de opmerking dat ze overruled kunnen worden in de filtering module die eraan komt. We moeten wel even zoeken waar deze voorbeelden nog te vinden zijn.
