### ISSUE TITLE
Tekstuele verbeteringen GEO module nav consultatie

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#487]
- [ ] 9. par 3.2: In de zin ""Exchange format (notation) RD and Pseudo Mercator X Y in meters: 195427.5200 311611.8400"" een komma toevoegen tussen de coordinaten ""195427.5200, 311611.8400"".
- [ ] 11.par 3.2: De zin ""Officially, WGS 84 lat-long (CRS84) is the only CRS allowed in GeoJSON."" aanpassen naar ""Officially, WGS 84 (CRS84) is the only CRS allowed in GeoJSON."" Het is long-lat en niet lat-long beter weglaten om verwarring te voorkomen.
- [ ] 18.mbt API-GEO-9: tekstueel: ""in a request parameter as a parameter"" dubbel op. voorstel: ""Support passing the coordinate reference system (CRS) of the geometry as a query parameter""
- [ ] 23. mbt API-GEO-11: tekstueel: -> Support passing the desired coordinate reference system (CRS) of the geometry in the response as a query parameter
- [ ] 24. par 3.3: De zin ""In case of a transformation between RD and ETRS89, it is highly recommended that this transformation uses the latest version of the procedure of RDNAPTRANS™."" aanpassen naar ""In case of a transformation between RD and ETRF2000, it is required that this transformation uses the latest version of the procedure RDNAPTRANS™.""

**Comment by strijm** [comment]
Opgelost dmv #511
