### ISSUE TITLE
Specifiek CRS opgeven

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#488]
10. par 3.2: De URIs van ETRF2000 zijn ""http://www.opengis.net/def/crs/EPSG/9.9.1/9067"" (2D) en ""http://www.opengis.net/def/crs/EPSG/9.9.1/7931"" (3D). Dit zijn specifiekere CRS-en van een ensemble, opnemen in de tabel als het advies wordt gegeven om een zo specifiek mogelijk CRS op te geven. ETRF2000 is de CRS die we in NL gebruiken.

**Comment by lvdbrink** [comment]
wordt al opgelost zie #534
