### ISSUE TITLE
Hoe specificeer je gewenste nauwkeurigheid?

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#491]
17. par 3.2: ""Exchange format (notation) ETRS89 and WGS84 longitude latitude in decimal degrees: DD.ddddddddd (for example: 5.962376256, 52.255023450)"" onduidelijk. Is dit een precision requirement? Hoe specificeer je gewenste nauwkeurigheid?

**Comment by PB-GNM** [comment]
Ik denk dat we erbij kunnen zetten dat het om een voorbeeld gaat en dat de Geomodule niets voorschrijft t.a.v. de nauwkeurigheid van de coördinaten. Dat hangt volledig van de toepassing af.

**Comment by lvdbrink** [comment]
Is al opgelost in #528 door bij het stukje over nauwkeurigheid een ref naar de HR CRS op te nemen.
