### ISSUE TITLE
HTTP POST

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#493]
- [ ] 20. par 3.2: tekstueel: ""In an API that supports transactions, POST requests with [...]"" Wat zijn transactions?
- [ ] 21. mbt API-GEO-10: Levert een POST altijd een HTTP 201?

**Comment by lvdbrink** [comment]
201 is 'created' - als een POST gelukt is krijg je een 201 terug, en je krijgt een referentie naar het object mee; als het niet gelukt is, krijg je een foutcode.
