### ISSUE TITLE
If no CRS is asserted, the default CRS, CRS84, is assumed.

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#494]
22. bmt API-GEO-10: Deze passage staat er wat verscholen: ""Alternatively, if the feature representation supports expressing CRS information for each feature / geometry, the information can also be included in the feature representation. If no CRS is asserted, the default CRS, CRS84, is assumed."" Daarnaast is het onduidelijk wat de normativiteit hiervan is.

**Comment by lvdbrink** [comment]
De regel API-GEO-7 stelt al dat CRS84 de default CRS is. In API-GEO-10 wordt dit nog eens herhaald. 

Ter verduidelijking maken we de volgende wijzigingen: 
- In API-GEO-7: aangeven dat dit ook geldt voor requests met een POST
- In API-GEO-10: verwijzen naar API-GEO-7.
