### ISSUE TITLE
Hoe specificeer je evt. gewenste nauwkeurigheid van CRS transformatie?

### ISSUE THREAD

**Issue by mrtn78** [Geonovum/KP-APIs#495]
25. Hoe specificeer je evt. gewenste nauwkeurigheid van CRS transformatie?

**Comment by strijm** [comment]
Dit issue kan worden gesloten. De opmerking gaat nl. niet zozeer over de nauwkeurigheid van een CRS transformatie maar over de nauwkeurigheid van coördinaten (zie #491). De nauwkeurigheid van coördinaten en transformaties wordt in de CRS handreiking nader toegelicht, daarom zal er een referentie naar worden opgenomen.
