### ISSUE TITLE
API-GEO-3: globaal zoeken op typering hoort niet thuis in de geo module.

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#496]
**Uit consultatie voortgekomen opmerking:**
API-GEO-3 Dit heeft betrekking op globaal zoeken en typering in het algemeen. Dit hoort niet thuis in de geo module.

**Comment by PB-GNM** [comment]
Als het er wel thuis hoort , zou dit dan niet in 2.3 Result (Response) moeten staan?

**Comment by lvdbrink** [comment]
De reviewopmerking is terecht. 

We voegen in de tekst een opmerking toe met de strekking dat zolang in de ADR niet centraal beschreven is hoe filtering/globaal zoeken werkt, we deze regel in stand houden.
