### ISSUE TITLE
API-GEO-4: Geldt deze eis ook voor andere media types dan application/json ?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#499]
**Uit consultatie voortgekomen opmerking:**
API-GEO-4 Geldt dit alleen voor application/json? of ook voor andere json (+json) based media types?

**Comment by lvdbrink** [comment]
M.i. geldt het ook voor andere JSON based media types, bv `application/ld+json`.

Het geldt alleen niet voor `application/geo+json` want daarvoor geldt GEO-API-1. 

Voorgestelde oplossing: We kunnen hier een toelichting over opnemen bij GEO-API-4.

**Comment by lvdbrink** [comment]
opgelost in #576
