### ISSUE TITLE
Proposal: API-42 verduidelijken

### ISSUE THREAD

**Issue by HenriKorver** [Geonovum/KP-APIs#50]
[Resultaten van een globale geometrische zoekvraag worden in de relevante geometrische context geplaatst](https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie/principes.md#api-42-resultaten-van-een-globale-geometrische-zoekvraag-worden-in-de-relevante-geometrische-context-geplaatst)

Dit principe is niet duidelijk en zou beter moeten worden uitgelegd in de tekst van sectie [Geo-ondersteuning](https://github.com/Geonovum/KP-APIs/blob/master/Werkgroep%20API%20strategie/Designrules%20v0.1.md#geo-ondersteuning)

**Comment by jasperroes** [comment]
Opgelost door voorbeeld toe te voegen.
