### ISSUE TITLE
API-GEO-4: Is de eis: "a property coordinates containing an array with a minimum of 2 numbers." wel zinvol?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#500]
**Uit consultatie voortgekomen opmerking:**
API-GEO-4 ""a property coordinates containing an array with a minimum of 2 numbers."" dit geldt niet voor alle geometry types?

**Comment by oddguid** [comment]
In RFC 7946 - The GeoJSON Format staat dit over een [position](https://www.rfc-editor.org/rfc/rfc7946#section-3.1.1):

*A position is an array of numbers.  There MUST be two or more
elements.  The first two elements are longitude and latitude, or
easting and northing, precisely in that order and using decimal
numbers.  Altitude or elevation MAY be included as an optional third
element.*

Dit komt overeen met API-GEO-4 ?

**Comment by lvdbrink** [comment]
17-1-2023 besproken in geo module werkgroep. Conclusie: de tekst van de eis klopt; de kleinste geometrie is een punt, deze heeft minimaal 2 getallen. We willen graag zo expliciet mogelijk zijn en handhaven deze regel daarom wel, net zoals GeoJSON dat doet.
