### ISSUE TITLE
Onduidelijkheid over endpoints voor collecties 

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#501]
**Uit consultatie voortgekomen opmerking:**
Het lijkt de melder vreemd dat iedere REST API die iets met geo doet een extra endpoint moet introduceren voor het opvragen van een lijst met collections, enkel en alleen voor het discoveren van CRSen. API's zijn vaak complexer opgebouwd dan simpelweg feature-collections en features. Wat stop je dan wel of niet in deze lijst? Ook niet-geo collecties of geneste collecties? Ik vraag mij af hoe zinvol dit is, als je niet ook alle andere standaard endpoints van OAF implementeert. Mogelijk aanpassen naar overnemen van bepaalde aspecten uit de discovery feature evt. ism andere meta gegevens over de serivce. "

**Comment by PB-GNM** [comment]
Gezien onderstaande genoemde eis in par 3.1 lijkt mij dit geen probleem:

***"According to [OGC API Features - part 1 - 7.13. Feature collections](https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_collections_) an OGC API Features API shall provide a GET operation on the /collections endpoint which returns a collections object."***

Als er geen endpoints met "/collections" in zitten is het dus ook geen OGC-API-Features services.
Als er naast de "/collections" nog andere endpoints in zitten die geen feature collections bevatten is het daarvoor ook niet verplicht, maar dat lijkt mij vrij logisch.

**Comment by lvdbrink** [comment]
2-2 besproken in werkgroep: 

Het is legitiem dat er ook APIs zijn die weliswaar objecten  met geometrieën serveren, maar niet OGC API Features-compliant zijn. Dit is het geval als de API niet gebruikt wordt vanuit GIS maar vanuit administratieve processen, zoals bv bij de BAG bevragingen API. 

Besluit: we herschrijven API-GEO-5: 
- ALS de API OGC API Features compliant is, dan moet je de /collections endpoint met de `crs` property ondersteunen; 
- ANDERS moet je een ander endpoint opnemen met de `crs` property en dit endpoint moet in je API spec staan zoals beschreven in [de paragraaf over API documentatie in de API Design Rules](https://publicatie.centrumvoorstandaarden.nl/api/adr/#documentation).

**Comment by strijm** [comment]
Opgelost door #578.
