### ISSUE TITLE
Waarom zou de API het CRS van opslag moeten ondersteunen?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#503]
**Uit consultatie voortgekomen suggestie:**
par 3.1: Waarom zou de API het CRS van opslag moeten ondersteunen? Er zijn (theoretische) gevallen waarin een specifiek CRS handig is voor opslag maar niet voor uitwisseling van data. Is deze eis noodzakelijk? Zo niet, dan kan deze in er uit: ""The value of this property shall be one of the CRSs supported by the API and advertised in the CRS list"". Aanbeveling van maken i.p.v. verplichting.

**Comment by strijm** [comment]
Uitleg toevoegen waarom de storage-crs parameter nodig is.
