### ISSUE TITLE
verduidelijking gewenst

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#505]
**Uit consultatie voortgekomen suggestie:**
par 3.2: De zin ""Thus, spatial data can be mapped without any complex transformations."" is geen logishc gevolg van ""Since most client-side mapping libraries use WGS 84, the W3C/OGC Spatial Data on the Web working group recommends to use this as the default coordinate reference system. "". Er moet duidelijker geformuleerd worden wat bedoeld wordt (of de zin verwijderd).

**Comment by strijm** [comment]
Opgelost dmv #523.
