### ISSUE TITLE
Waarom moet "Pseudo Mercator" altijd ondersteund worden?

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#506]
**Uit consultatie voortgekomen suggestie:**
par 3.2: Waarom moet ""Pseudo Mercator"" altijd ondersteund worden? De ""Handreiking CRS ([hr-crs]) zegt over ""Pseudo Mercator"" dat het ""alleen geschikt [is voor] eenvoudige visualisatie van onnauwkeurige data"". Voor data die niet bedoelt zijn voor visualisatie is ""Pseudo Mercator"" dus onwenselijk in een API. Psuedo mercator wel aanbevelen als één van de opties voor visualisaties.

**Comment by lvdbrink** [comment]
> In 3.2 staat: The API strategy caters for this supporting not only ETRS89 and RD/Amersfoort, but also WGS84 and Pseudo Mercator (EPSG:3857).

Uit deze zin moeten we Pseudo Mercator verwijderen, EN ook in 3.2 2x verwijderen uit de bullet list onder "The guiding principles for CRS support". 

Wel een zinnetje toevoegen waarin we pseudo mercator wel aanbevelen als één van de opties voor visualisaties, voor de use case waarin men een web client met een kaartje wil maken obv je API.

**Comment by strijm** [comment]
Opgelost dmv #511.
