### ISSUE TITLE
Zin over "Use RDNAPTRANS™ 2018" aanpassen.

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#507]
**Uit consultatie voortgekomen suggestie:**
par 3.2: De zin ""Use RDNAPTRANS™ 2018 to transform RD/Amersfoort to ETRS89 (correction grid);"" aanpassen naar ""Use the latest version of RDNAPTRANS™ to transform RD to ETRF2000 (including correction grid for the highest accuracy);"" (dit maakt het consistent met een vergelijkbare passage later in de tekst). Amersfoort weglaten en geen versie van RNAPTRANS noemen vanwege onderhoudbaarheid, laatste versie gebruiken.

**Comment by sweco-nlgemo** [comment]
In de tekstsuggestie wordt ook ETRS89 vervangen door ETRF2000, is dat de bedoeling?

**Comment by PB-GNM** [comment]
Ik ben het eens met Linda, maar denk wel dat we elders in de tekst moeten opnemen wat realisaties van een CRS eigenlijk zijn en waarom we ze hier niet noemen.
Dan kunnen we verwijzen naar: https://docs.geostandaarden.nl/crs/crs/#realisatie-van-het-crs.

**Comment by lvdbrink** [comment]
Ja, inderdaad. Concreet is het dan misschien goed om een Noot op te nemen. Voorzetje:

> **Noot**
> De definitie van een CRS geeft een verzameling afspraken over bijvoorbeeld de oorsprong, oriëntatie, schaal, naamgeving van de coördinaatassen. Om een CRS te kunnen gebruiken, moeten de coördinaten eenmalig ten opzichte van fysieke referentiepunten daadwerkelijk worden vastgesteld. Voor zeer nauwkeurige toepassingen kan het relevant zijn naar een specifieke realisatie van het CRS te verwijzen. In plaats van ETRS89 verwijs je dan bijvoorbeeld naar de specifieke realisatie ETRF2000. 

> Zie voor meer informatie [de paragraaf over CRS realisatie in de handreiking CRS](https://docs.geostandaarden.nl/crs/crs/#realisatie-van-het-crs)
