### ISSUE TITLE
Punt toevoegen aan "the guiding principles for CRS support".

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#508]
**Uit consultatie voortgekomen suggestie:**
par 3.2: Aan ""the guiding principles for CRS support"" dit punt toevoegen ""Use a nulltransformation to transform ETRF2000 to WGS 84 unless a time-dependent transformation is needed, see the CRS Guidelines [hr-crs]. If a time-dependent transformation is used for WGS 84, the CRS used as realisation of WGS 84 should be supported by the API too, e.g. if the transformation between ETRF2000 and ITRF2014 at epoch 2020 is used for request/response in WGS 84 (EPSG:4326), then the API should also support ITRF2014 (EPSG:9000)."" Het advies is om altijd de meest specifieke CRS aan te geven en niet allen het ensemble zoals WGS84 of ETRS89.

**Comment by PB-GNM** [comment]
**Uit consultatie voortgekomen suggestie:**
par 3.2: In toevoeging op boven gestelde opmerking over time-dependent transformation zou het volgende toegevoegd kunnen worden als eis: When the API provides data in an ensemble CRS like WGS 84 or ETRS89 while it is known to what ensemble member CRS the data actaully refers to, this ensemble member should also be one of the CRSs supported by the API and advertised in the CRS list. E.g. when 2D data is transformed from RD with RDNAPTRANS not only EPSG::4258 should be supported but also EPSG::9067.

**Comment by strijm** [comment]
Opgelost dmv #512.
