### ISSUE TITLE
API-GEO-4 kan ook van toepassing zijn op request

### ISSUE THREAD

**Issue by sweco-nlgemo** [Geonovum/KP-APIs#519]
API-GEO-4 staat in het hoofstuk *Request and response* onder de paragraaf *Result (response)*, maar deze regel is volgens mij ook toepasbaar op een request waarin geometrie is opgenomen. 

Heeft het zin om deze API regel een andere plaats te geven? De titel van de paragraaf aanpassen is ook een optie

**Comment by sweco-nlgemo** [comment]
In hetzelfde bestand (`request-response.md`) staat in de inleiding deze tekst:

> This module does not describe how to supply a geometry as part of a resource for storage, i.e. when creating, replacing or updating resources. [OGC API Features part 4](http://docs.ogc.org/DRAFTS/20-002.html), which is still in development, will address this.

Dit lijkt aan te geven dat geometrie in requests niet uitgewerkt wordt in deze geo module en dan zou het opnemen van een regel over het embedden van GeoJSON in een request tegenstrijdig zijn. Of lees ik het verkeerd?

Aan de andere kant wordt in `crs.md` in de tabel met scenario's wel geometrie in een request body genoemd.

Ik weet nu niet of dit issue uitgewerkt moet worden in een extra regel.

**Comment by lvdbrink** [comment]
Je hebt hier een inconsistentie in de geo-module te pakken. Inderdaad zeggen we in het begin van hfd 2, in de Note, dat we geometrie in requests nog niet uitwerken. Maar in 3.2 in API-GEO-11 geven we wel degelijk een regel voor geometrie in requests. 

We kunnen m.i. kiezen: 
- optie 1: we handhaven onze Note dat we geometrie in requests nog niet uitwerken. Dan schrappen we voor nu API-GEO-11 en nemen we ook geen nieuwe regel op voor requests met geometrie;
- optie 2: we schrappen onze Note  dat we geometrie in requests nog niet uitwerken. Dan handhaven we API-GEO-11 en nemen we wel een nieuwe regel op voor requests met geometrie. Dan geldt wel wat we daarnet bespraken: voor een request waarmee we een resource met geometrie toevoegen of wijzigen gebruiken we GeoJSON in de request, maar voor filters niet, want dat kan conflicteren met OGC API Features deel 4.

**Comment by lvdbrink** [comment]
... nou heb ik nog open gelaten wat we daadwerkelijk gaan doen: hier mogen we allemaal over meedenken.

Ik heb toch wel voorkeur voor optie 1, dat kost minder tijd en is meer in lijn met ons plan om filtering en CRUD later uit te werken.

**Comment by PB-GNM** [comment]
Ik ben ook voor optie 1, waarbij het denk ik wel goed is om in de verwijzing naar [OGC API Features part 4](http://docs.ogc.org/DRAFTS/20-002.html) ook op te nemen in de references net als part 1 t/m 3.

**Comment by strijm** [comment]
Als we alleen bepaalde onderwerpen uit OGC API Features beschrijven, zoals CRS discovery, CRS negotiation en eenvoudige filtering o.b.v. bbox en de complexe filtering en create, update en delete niet beschrijven omdat die OGC API Features documenten nog niet definitief zijn, wat is dan de meerwaarde van de geo-module?

Ik denk dat we ook hier onderscheid kunnen maken tussen wel of niet OGC API Features compliant zijn bv. als een API  gebruikt wordt in GIS applicaties resp. het gebruik in bv. administratieve toepassingen, daar zit m.i. de meerwaarde van de geo module. Bij administratieve toepassingen moeten resources meestal worden uitgewisseld conform een vastgesteld informatiemodel waarbij geometrie een attribuut van een resource kan zijn. OGC API Features beschrijft voornamelijk features en features collections die meestal niet overeenkomen met de resources zoals gedefinieerd in een informatiemodel.
Van complexe filtering hebben we al gezegd dat we dat apart oppakken. 
Voor administratieve toepassingen kunnen we m.i. beschrijven hoe resources met geometrie bij creëren, updaten of deleten worden uitgewisseld.

Kortom ik denk dat er een derde optie is: het nuanceren van de note en toch voorbeelden opnemen hoe resources met geometrie aangeboden worden bij een HTTP POST, PUT, DELETE etc. waar OGC API Features compliancy geen eis is of zelfs niet mogelijk is, zoals bv. bij administratieve toepassingen.

**Comment by lvdbrink** [comment]
> Als we [...] complexe filtering en create, update en delete niet beschrijven omdat die OGC API Features documenten nog niet definitief zijn, wat is dan de meerwaarde van de geo-module?
Niet zozeer omdat die OGC documenten nog niet definitief zijn; maar omdat er plannen zijn om nieuwe ADR extensies te schrijven over filtering en CRUD. Tenminste, ik meen me te herinneren dat er voor create/update/delete ook eentje zou komen en met dat in mijn achterhoofd had ik de neiging om regels daarover uit te stellen. 

Echter, het kan goed zijn dat dat nog wel even gaat duren, omdat waarschijnlijk Filtering eerst opgepakt wordt en best tijd zal kosten. 

Dus bij nader inzien kunnen we dit wel oppakken. Dan: 
- de noot nuanceren (dwz we beschrijven wel hoe je met geodata in een create/update request om gaat, maar wijzen er ook op dat de OGC standaard daarvoor nog niet gereed is)
- voor administratieve toepassingen beschrijven hoe resources met geometrie bij create/update/delete worden uitgewisseld. Ik zou dit wel willen baseren op OGC API Features deel 4 tenzij dat heel erg afwijkt van wat je normaal zou doen in een administratieve api. 
-  daarnaast beschrijven hoe je het in een OGC API Features doet (met nogmaals waarschuwing dat dit nog zou kunnen veranderen) - als dit anders is dan we voor admin api's beschrijven.
