### ISSUE TITLE
Gebruik van RFC2119 voor keywords in requirements

### ISSUE THREAD

**Issue by strijm** [Geonovum/KP-APIs#521]
Verzoek om te besluiten [RFC (2119](https://www.ietf.org/rfc/rfc2119)) te gebruiken voor keywords als MAY, MUST, SHOULD etc. in requirements definities, indien dat nog niet is gedaan.
Dit besluit vast te leggen en een korte beschrijving en referentie naar de RFC in de core op te nemen, zodat dit niet in iedere afzonderlijk module gebeurt.

Zie ook #475.

**Comment by mrtn78** [comment]
Gezien de impact van dit punt is dit een aandachtspunt voor de Stuurgroep. Mijn verwachting is dat dit zeker een verbetering is maar dat je dit dan voor alle rules moet toepassen. daarmee is het een grote wijziging en alleen haalbaar als er voldoende mensen beschikbaar zijn om alle rules aan te passen zonder dat dit vertraging veroorzaakt bij de andere ontwikkelingen.

**Comment by mrtn78** [comment]
doorgevoerd in ADR 2
