### ISSUE TITLE
Standaardiseren Logging

### ISSUE THREAD

**Issue by fterpstra** [Geonovum/KP-APIs#549]

**Comment by fterpstra** [comment]
3 stemmen op 3 feb

**Comment by edwinwisse** [comment]
VNG en RINIS hebben een vernieuwingsvoorstel "Digikoppeling APIs" ingediend om de ontwikkelingen in NLX/FSC in Digikoppeling REST API spec te laten landen. Standaardisatie van logging is één van de zaken die ze aan willen pakken. Het lijkt ons nuttig als voorstellen in die richting in de ADR landen en niet alleen in Digikoppeling REST API.

**Comment by mrtn78** [comment]
gesloten in overleg 13-05-2024
