### ISSUE TITLE
Lijst van ensemble- en member CRSsen

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#563]
Voor het kunnen valideren van de test van GEO-API-9 is het nodig om een lijst te hebben van voor Nederlandse context relevante ensemble CRSsen met hun bijbehorende member CRSsen. 

Deze lijst hoeft niet per sé in de geo module te worden opgenomen, maar wel in ieder geval als antwoord op dit issue worden vastgelegd.

**Comment by lvdbrink** [comment]
Oplossen door verwijzing naar CRS handreiking.

**Comment by lvdbrink** [comment]
En een issue over de CRS handreiking inschieten met het verzoek om de URIs van CRSsen op te nemen in de tabel achterin.

**Comment by PB-GNM** [comment]
Ik heb een issue aangemaakt op de HR-CRS-Gebruik repository:
https://github.com/Geonovum/HR-CRS-Gebruik/issues/22

**Comment by strijm** [comment]
Opgelost met #575.
