### ISSUE TITLE
laatste controle op versie ter vaststelling geomodule 14 april

### ISSUE THREAD

**Issue by PB-GNM** [Geonovum/KP-APIs#597]
N.a.v. de laatste controle op versie ter vaststelling geomodule 14 april https://docs.geostandaarden.nl/api/API-Strategie-mod-geo/
Heb ik nog het volgende geconstateerd:

- In paragraaf 1 staat een noot over RD, maar dat past daar niet. Kan het nog verplaatst worden naar het begin van paragraaf 3 waar die beter past?.
- In paragraaf 2.2 staat onder example 1: "it is up to the provider to decide if **a** single or multiple geometries are returned". Ik zou de "a" voor single weghalen.
-  In paragraaf 2.2 staat de volgende noot: "Spatial operations like intersects and within in combination with a filter geometry (e.g. bbox) or resource geometry containing lines with a length > 200 m, may result in erroneous responses, see [vormvastheid](https://docs.geostandaarden.nl/crs/cv-hr-crs-20211125/#vormvastheid) (Dutch)".
Ik zou deze noot weglaten, want hij is alleen aan de orde als er sprake is van transformaties en ook nog eens afhankelijk van de schaal en nauwkeurigheid waarop je werkt. Het is nu een uit de context gehaalde opmerking die veel meer uitleg nodig heeft. Die uitleg wordt wel gegeven in in de handreiking over CRSs.
- Paragraaf 3.2.1 lijkt een foutje en moet helemaal geen paragraaf zijn. daar boven staat ook "div class="rule" id="ensemble-member-crs">" Daar gaat iets mis, want requirement "emsemble-member-crs" zou eigenlijk blauw moeten zijn.
-  In paragraaf 4 staat: "a special working group has worked on a". Beter is om dit te vervangen door: "an endorsed good practice has been described in a".

**Comment by strijm** [comment]
Deze noot heb ik toegevoegd n.a.v. review opmerkingen (zie #590). Ik zou deze dus niet zomaar weglaten. 
Dan is het misschien beter om iets meer uitleg te geven zoals beschreven in #590, misschien heb ik hier iets te veel weggelaten. 
De noot is dus niet alleen aan de orde bij transformaties. Deze noot gaat juist over de spatial operators en dat deze (mede door te lange lijnen) in de zoekgeometrie of in de geometrie waarnaar wordt gezocht afwijkingen kan veroorzaken. 
Als er met een bbox wordt gezocht met zijden langer dan 200 meter of object geometrieën bevatten lijnen langer dna 200 meter, dan zit er een afwijking in. Als een object geometrie buiten de bbox ligt en de geometrie raakt de bbox zonder lange lijnen correctie niet en met lange lijnen correctie wel, dan wordt het object zonder lange lijnen correctie niet geretourneerd. 
Naarmate de bbox zijden of lijnen van een object geometrie langer worden, neemt de afwijking toe, ook bij minder nauwkeurige CRS-en neemt de afwijking toe.
Voorbeelden:
- Als met een bbox 200 x 200 met RD coördinaten wordt gezocht dan is het resultaat van spatial operaties nauwkeuriger dan wanneer er wordt gezocht met een bbox 1000 x 1000 m met RD coördinaten.
- Als een object geometrie lijnstukken bevat van 200 meter dan is het resultaat van spatial operaties nauwkeuriger dan wanneer de object geomtrie lijnstukken bevat van 1000 meter.
- Als met een bbox 1000 x 1000 m met RD coördinaten wordt gezocht naar objecten met geometrie in RD coördinaten zal dit nauwkeurigere resultaten opleveren dan wanneer er met dezelfde geometrie maar dan met CRS84 coördinaten wordt gezocht naar geometrieën die van RD naar CRS84 zijn getransformeerd.
De noot gaat dus meer over de spatial operators en de mogelijke afwijkingen, dan over transformatie (maar is daar in zekere zin wel aan gerelateerd). De noot is niet bedoeld om in de geomodule de volledige uitleg te geven, maar meer om men ervan bewust te maken dat er afwijkingen kunnen ontstaan en hoe deze afwijkingen ontstaan, vandaar de verwijzing naar het CRS document.

**Comment by lvdbrink** [comment]
Met deze uitleg van @strijm stel ik voor om de Noot te handhaven. 

Ik zal alleen de verwijzing naar de Handreiking CRS iets duidelijker maken. Dat wordt dan: 

"... erroneous responses, see the **[explanation in the Handreiking CRS](https://docs.geostandaarden.nl/crs/cv-hr-crs-20211125/#vormvastheid)**".
