### ISSUE TITLE
Redactioneel commentaar op API designrules 2.0 

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/KP-APIs#607]
- 'actual' in het Engels betekent niet hetzelfde als 'actueel' in het Nederlands. In 1.4 Reading Guide, in de zin "An actual overview of all current documents is available in this Dutch infographic" zou ik het woord 'actual' schrappen. 
- de Note in 2. Summary is achterhaald. Rules worden niet meer genummerd. 
- rule `/core/no-trailing-slash`: de tekst onder Statement en onder Rationale zijn bijna kopieën van elkaar. Suggestie: onder Statement de zin "This enforces API consumers to use the correct URI." verwijderen. Onder Rationale de tekst als volgt wijzigen (suggestie): "Leaving off trailing slashes, and not implementing a redirect, enforces API consumers to use the correct URI. This avoids confusion and ambiguity."

**Comment by sanderke** [comment]
Staat nu in de werkversie.
