### ISSUE TITLE
4.3.1: geen toestand & cookies of sessies 

### ISSUE THREAD

**Issue by mevdschee** [Geonovum/KP-APIs#61]
>Een REST API mag geen toestand (state) bijhouden. Dit betekent dat authenticatie en autorisatie van een verzoek niet mag afhangen van cookies of sessies. In plaats daarvan wordt elk verzoek voorzien van een token.

Een session-token (in een cookie) en een API-token in een (custom) HTTP header verschillen conceptueel van elkaar door het transportprotocol. Beide transportprotocollen hebben voor en nadelen:

HTTP-only cookies kunnen niet door JavaScript gelezen worden en zijn dus minder vatbaar voor XSS. Cookies worden automatisch verstuurd, dus dat maakt ze kwetsbaar voor CSRF. Hier heeft een (custom) HTTP header value geen last van.

Ik zou het beter vinden als het transport (cookies) hier niet in een negatieve manier genoemd wordt en het onderscheid tussen transport en algoritme (signed token vs. server state) duidelijker wordt gemaakt.

**Comment by mevdschee** [comment]
Toevoeging: Ook kan je je afvragen of state ten (behoeve van authenticatie en autorisatie) niet toch wenselijk/toegestaan moet zijn, aangezien goede signature verificatie algorithmen een significante overhead hebben. Door een RSA verificatie van het JWT token op elke request te doen verbruik je erg veel CPU. Een tijdelijk geldig session-id of unsigned API token is dan een praktische oplossing, maar deze vereisen wel server-state.

**Comment by bartjkdp** [comment]
In principe vind ik stateless een goed uitgangspunt voor API's. Maar ik ben het ook met @mevdschee eens dat bij het ontwerpen van een API voor een Javascript client het gebruik van een HTTP-only cookie soms wenselijk kan zijn.

**Comment by mevdschee** [comment]
@bartjkdp Ik vind stateless ook een goed uitgangspunt voor API's en dat wil ik ook zeker niet ter discussie stellen, goed dat je dat nog even benoemt.

**Comment by joostfarla** [comment]
Discussie wordt vervolgd in issue #193.
