### ISSUE TITLE
Link incorrect in Access Control

### ISSUE THREAD

**Issue by brinm00** [Geonovum/KP-APIs#612]
The URL (https://geonovum.github.io/KP-APIs/Werkgroep%20API%20architectuur/) in par 2.2 results in a 404 file not found.

**Comment by brinm00** [comment]
For completeness: the issue is found on https://geonovum.github.io/KP-APIs/API-strategie-modules/access-control/

**Comment by mrtn78** [comment]
I've scanned the document for broken and old links. fixed in commit: https://github.com/Geonovum/KP-APIs/commit/8bf07ec1935f9985c8e45949b7d9dfe328c87a51
