### ISSUE TITLE
6.1.11 verbinding is altijd versleuteld met TLSv1.2. Welke verbinding? met wie?

### ISSUE THREAD

**Issue by PieterHering** [Geonovum/KP-APIs#63]
Dit principe gebruikt de term: “de verbinding” maar vermeldt niet tussen welke partijen  de verbinding is gelegd. Gaat het altijd om verbinding met "derden"? Gaat het om twee organisaties gescheiden door een extern netwerk zoals Diginetwerk of Internet? Is het raadzaam om transportbeveiliging obv TLSv1.2 ook toe te passen op intern verkeer? 

Vermijd verwarring door deze regel aan te scherpen.

**Comment by fterpstra** [comment]
Vanuit de werkgroepbeveiliging ondersteunen we deze opmerking. Neem bij je aanbevelingen mee voor welke usecases ze van toepassing zijn.

**Comment by jasperroes** [comment]
Verwerkt in beveiliging extensie.
