### ISSUE TITLE
Suggesties voor hoofdstuk 2 (Communicatie & Beleid)

### ISSUE THREAD

**Issue by ForumStandaardisatie** [Geonovum/KP-APIs#74]
Hoofdstuk 2 bevat veel algemene tekst. Zelfs de voorbeelden in 2.9 zijn nogal algemeen. Het hoofdstuk kan scherper, concreter en beknopter. Suggestie is om twee of drie duidelijke en aansprekende voorbeelden te pakken en het verhaal daar aan op te hangen. Die voorbeelden hoeven niet alleen van de overheid te zijn. Laat met de voorbeelden zien wat je met APIs kan dat vroeger niet kon. Gebruik ook illustraties waar dat helpt. Aanvullende suggesties:

- Paragraaf 2.2: De introductie kan sterker, direct met een aansprekend voorbeeld beginnen in plaats van algemene zinnen van de strekking “online platformen worden steeds belangrijker”.
- Paragraaf 2.3: De definitie van APIs kan aansprekender voor niet-technische mensen. Suggestie: “Een API is een via Internet toegankelijk koppelvlak voor applicaties. Een API is voor machine-machine communicatie wat een website voor machine-mens communicatie is.” Wellicht ook met een plaatje illustreren? 
- Paragraaf 2.3: Prestaties en schaalbaarheid zijn geen unieke eigenschappen van APIs. Dat zou ik hier ook niet noemen. Wat uniek is aan APIs is dat het de mechanismen van het world wide web gebruikt voor machine-machine communicatie.
- Paragraaf 2.4: de stelling “de opkomst van de API begon rond 2008” is waar voor RESTful APIs, maar daarvoor waren er al Web Services die al bijna 10 jaar APIs implementeerden. Daarom is de zin die erop volgt wat overdreven. Het Internet werd al ruim voor 2008 veel gebruikt voor machine-machine communicatie.
- Paragraaf 2.5: Dit zijn nogal algemene punten. Voorbeelden zouden hier heel erg helpen. Bijvoorbeeld Common Ground.
- Paragraaf 2.6: leg hier uit dat APIs voor developers zijn wat websites voor burgers zijn.

**Comment by mrtn78** [comment]
Dit hoofdstuk is inmiddels herschreven
