### ISSUE TITLE
Suggesties voor hoofdstuk 3 (Gebruikerswensen)

### ISSUE THREAD

**Issue by ForumStandaardisatie** [Geonovum/KP-APIs#75]
Hoofdstuk 3 heeft het over ‘de gebruiker’. Maak in de inleiding duidelijker wie de ‘gebruikers’ van APIs zijn. Bij het woord 'gebruiker' kan de lezer onterecht denken aan eindgebruikers van de applicaties die van de APIs gebruik maken. Paragraaf 3.4.1 versterkt deze interpretatie door te stellen dat je APIs voor mensen maakt. Bovendien lijkt een product manager meer een gebruiker van de documentatie die bij een API wordt geleverd, dan van de API zelf. Dit geldt vermoedelijk ook voor de architect.

Aanvullende suggesties:

- De kern van hoofdstuk 3 zit in paragraaf 3.4. De rest kan korter, concreter en scherper.
- Het gebruik van user stories is leuk. Misschien nog effectiever is het als je echte ervaringen kan optekenen. Nu leest het toch nog als fictie.
- Paragraaf 3.4.4: Leg kort uit wat een Sandbox is.
- Paragraaf 3.4.6: Hier wordt heel vluchtig gepraat over het ‘vastleggen van semantiek’. Graag meer concrete suggesties hoe men dit kan doen, wellicht met een voorbeeld?
- Paragraaf 3.4.8: Of een API de juiste toegangsmethode is, is vooral een vraag voor System APIs.

**Comment by frisopenninga** [comment]
Opmerkingen grotendeels verwerkt:
- gebruiker direct in inleiding uitgelegd: gebruiker = developer, is intermediair naar eindgebruiker van uiteindelijke toepassing
- 3.1 t/m 3.3 korter: niet gedaan, pleidooi voor onze benadering van API's raakt de kern van onze boodschap. Willen we niet beknopter, zijn van mening dat dit pleidooi nodig is om kern van onze concrete aanbevelingen te kunnen duiden en op waarde te schatten
- user stories: op de namen na, komen deze processen uit de ervaring van een leverancier. 
- korte uitleg sandbox toegevoegd
- semantiek: online publiceren, bijv. Stelselcatalogus Omgevingswet
- API juiste methode: klopt dat vooral vraag is voor System API's. Maar als we dat benoemen, lopen we het risico dat het beeld ontstaat dat System API's niet nodig zijn en alleen Convenience API's. Als je dat ook weer moet duiden, wordt het te lang.
