### ISSUE TITLE
Laat paragraaf 6.2 weg tot er een duidelijke visie over architectuur is

### ISSUE THREAD

**Issue by ForumStandaardisatie** [Geonovum/KP-APIs#77]
In de huidige vorm past paragraaf 6.2 niet goed bij de rest van de API strategie. Hoofdstukken 1-5 gaan over APIs zelf, paragraaf 6.2 gaat meer over hoe je APIs moet gebruiken in diensten.
Waar APIs alleen het koppelvlak beschrijven, bemoeit het hoofstuk ‘Architectuur’ zich met hoe organisaties hun architecturen moeten inrichten voor APIs.
Daarbij lijkt paragraaf 6.2 zich vooral te richten op overheidsdiensten gebaseerd op basisregistraties, terwijl APIs voor meer gebruikt kunnen worden. Door vaste patronen te gaan beschrijven (6.2.8.2-6.2.8.4) zou de indruk kunnen ontstaan dat de API strategie wil inperken waarvoor en hoe APIs gebruikt worden.
Het Forum Standaardisatie ervaart dat overheidsorganisaties snel in de weerstand schieten als je ze gaat voorschrijven hoe ze hun architecturen of processen moeten inrichten. Het risico bestaat dat de hele API strategie wordt verworpen terwijl eigenlijk alleen de architectuur weerstand oproept. Het advies is daarom om paragraaf 6.2 in de huidige vorm daarom niet op te nemen. Of stel heel duidelijk dat dit hoofdstuk ter informatie is en geen deel uitmaakt van de API strategie.

**Comment by PHaasnoot** [comment]
Dit issue heeft betrekking op een eerdere draft versie van het hoofdstuk en kan gesloten worden
