### ISSUE TITLE
Geo extensie

### ISSUE THREAD

**Issue by jasperroes** [Geonovum/KP-APIs#93]
Opmerking ontvangen via review-formulier:

Het maken van een apart POST endpoint voor geografische query's voelt vreemd. Het lijkt me dat de meeste REST API's niet bedoeld zijn voor complexe geografische queries. Daarnaast lijkt het me handig als hier aangesloten wordt bij de WFS 3.0 standaard, waarbij je bijvoorbeeld wel een 'bounding box' via een GET kan benaderen. Dit lijkt me voor de meeste toepassingen afdoende, zonder dat je API developers een apart endpoint laat bouwen, waarbij API ontwikkelaars weer op moeten aansluiten.

Voorgestelde oplossing: Meer aansluiting zoeken bij WFS 3.0. Daarnaast ook 'bbox' als GET filter parameter voor eenvoudige geografische queries beschrijven.

**Comment by lvdbrink** [comment]
Zie #281

**Comment by lvdbrink** [comment]
`bbox` toegevoegd in https://github.com/Geonovum/KP-APIs/pull/434. 

Bredere discussie over POST en geografische en andere filters moet buiten de geo extensie werkgroep plaatsvinden. Zie hiervoor https://github.com/Geonovum/KP-APIs/issues/184#issuecomment-1070791689.

Deze kan dicht.
